---
# Base configuration handlers

- name: save opnsense config
  ansible.builtin.uri:
    url: "https://{{ opnsense_api.host }}:{{ opnsense_api.port }}/api/core/backup/backupconfig"
    method: POST
    validate_certs: "{{ opnsense_api.verify_ssl }}"
    force_basic_auth: true
    user: "{{ opnsense_api.username }}"
    password: "{{ opnsense_api.password }}"
    body_format: json
    body:
      description: "Configuration saved by Ansible handler"
    status_code: 200
  delegate_to: localhost

- name: restart ssh service
  ansible.builtin.uri:
    url: "https://{{ opnsense_api.host }}:{{ opnsense_api.port }}/api/core/service/restart/ssh"
    method: POST
    validate_certs: "{{ opnsense_api.verify_ssl }}"
    force_basic_auth: true
    user: "{{ opnsense_api.username }}"
    password: "{{ opnsense_api.password }}"
    status_code: 200
  delegate_to: localhost