---
# Backup tasks for semaphore

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ semaphore_data_dir }}/backups"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Set backup timestamp
  ansible.builtin.set_fact:
    backup_timestamp: "{{ ansible_date_time.epoch }}"

- name: Backup Semaphore database (SQLite)
  ansible.builtin.copy:
    src: "{{ semaphore_db_path }}"
    dest: "{{ semaphore_data_dir }}/backups/semaphore-db-{{ backup_timestamp }}.db"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  when: semaphore_db_type == 'sqlite'

- name: Backup Semaphore configuration
  ansible.builtin.copy:
    src: "{{ semaphore_config_file }}"
    dest: "{{ semaphore_data_dir }}/backups/config-{{ backup_timestamp }}.json"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create backup archive
  ansible.builtin.archive:
    path:
      - "{{ semaphore_data_dir }}/repositories"
      - "{{ semaphore_data_dir }}/backups/semaphore-db-{{ backup_timestamp }}.db"
      - "{{ semaphore_data_dir }}/backups/config-{{ backup_timestamp }}.json"
    dest: "{{ semaphore_data_dir }}/backups/semaphore-backup-{{ backup_timestamp }}.tar.gz"
    format: gz
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Remove temporary backup files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ semaphore_data_dir }}/backups/semaphore-db-{{ backup_timestamp }}.db"
    - "{{ semaphore_data_dir }}/backups/config-{{ backup_timestamp }}.json"

- name: Remove old backups
  ansible.builtin.find:
    paths: "{{ semaphore_data_dir }}/backups"
    patterns: "semaphore-backup-*.tar.gz"
    age: "{{ semaphore_backup_retention_days }}d"
  register: old_backups

- name: Delete old backup files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_backups.files }}"
  when: old_backups.files | length > 0