---
# Configuration tasks for semaphore

- name: Generate Semaphore configuration
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ semaphore_config_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    backup: true
  no_log: true

- name: Initialize SQLite database (if using SQLite)
  ansible.builtin.file:
    path: "{{ semaphore_db_path }}"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  when: semaphore_db_type == 'sqlite'

- name: Create MySQL database (if using MySQL)
  community.mysql.mysql_db:
    name: "{{ semaphore_db_name }}"
    state: present
    login_host: "{{ semaphore_db_host }}"
    login_port: "{{ semaphore_db_port }}"
    login_user: "{{ semaphore_db_user }}"
    login_password: "{{ semaphore_db_password }}"
  when: semaphore_db_type == 'mysql'
  no_log: true

- name: Create PostgreSQL database (if using PostgreSQL)
  community.postgresql.postgresql_db:
    name: "{{ semaphore_db_name }}"
    state: present
    login_host: "{{ semaphore_db_host }}"
    port: "{{ semaphore_db_port }}"
    login_user: "{{ semaphore_db_user }}"
    login_password: "{{ semaphore_db_password }}"
  when: semaphore_db_type == 'postgres'
  no_log: true