---
# Deployment tasks for semaphore

- name: Pull Semaphore image
  community.docker.docker_image:
    name: "{{ semaphore_container_image }}"
    source: pull
    state: present
  become: true

- name: Deploy Semaphore container
  community.docker.docker_container:
    name: "{{ semaphore_container_name }}"
    image: "{{ semaphore_container_image }}"
    state: started
    restart_policy: "{{ semaphore_container_restart_policy }}"
    networks:
      - name: "{{ semaphore_network_name }}"
    ports:
      - "{{ semaphore_web_port }}:3000"
    volumes:
      - "{{ semaphore_config_file }}:/etc/semaphore/config.json:ro"
      - "{{ semaphore_data_dir }}/tmp:/tmp/semaphore"
      - "{{ semaphore_data_dir }}/repositories:/var/lib/semaphore"
      - "{{ semaphore_db_path }}:/var/lib/semaphore/database.db"
    env_file: "{{ semaphore_data_dir }}/.env"
    labels:
      service: "semaphore"
      role: "management"
      managed_by: "ansible"
  become: true
  register: semaphore_container
  when: semaphore_db_type == 'sqlite'

- name: Deploy Semaphore container (MySQL/PostgreSQL)
  community.docker.docker_container:
    name: "{{ semaphore_container_name }}"
    image: "{{ semaphore_container_image }}"
    state: started
    restart_policy: "{{ semaphore_container_restart_policy }}"
    networks:
      - name: "{{ semaphore_network_name }}"
    ports:
      - "{{ semaphore_web_port }}:3000"
    volumes:
      - "{{ semaphore_config_file }}:/etc/semaphore/config.json:ro"
      - "{{ semaphore_data_dir }}/tmp:/tmp/semaphore"
      - "{{ semaphore_data_dir }}/repositories:/var/lib/semaphore"
    env_file: "{{ semaphore_data_dir }}/.env"
    labels:
      service: "semaphore"
      role: "management"
      managed_by: "ansible"
  become: true
  register: semaphore_container
  when: semaphore_db_type != 'sqlite'

- name: Wait for Semaphore to be ready
  ansible.builtin.uri:
    url: "http://localhost:{{ semaphore_web_port }}/api/ping"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 2

- name: Display Semaphore access information
  ansible.builtin.debug:
    msg:
      - "Semaphore has been successfully deployed!"
      - "Access URL: http://{{ ansible_host }}:{{ semaphore_web_port }}"
      - "Container ID: {{ semaphore_container.container.Id[:12] }}"
      - "Admin user: {{ semaphore_admin_user }}"
      - "Admin email: {{ semaphore_admin_email }}"