---
# tasks file for semaphore

- name: Include validation tasks
  ansible.builtin.include_tasks: validate.yml
  tags:
    - semaphore
    - semaphore-validate

- name: Include preparation tasks
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - semaphore
    - semaphore-prepare

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags:
    - semaphore
    - semaphore-configure

- name: Include deployment tasks
  ansible.builtin.include_tasks: deploy.yml
  tags:
    - semaphore
    - semaphore-deploy

- name: Include initial setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - semaphore
    - semaphore-setup

- name: Include backup tasks
  ansible.builtin.include_tasks: backup.yml
  when: semaphore_backup_enabled | bool
  tags:
    - semaphore
    - semaphore-backup