---
# Main Infrastructure Provisioning Playbook
# Provisions core infrastructure on Proxmox hosts

- name: Provision Infrastructure on Proxmox
  hosts: proxmox_hosts
  gather_facts: true
  tags:
    - infrastructure
    - provisioning
  
  pre_tasks:
    - name: Validate Proxmox connectivity
      ansible.builtin.ping:
      register: ping_result
      failed_when: false
    
    - name: Fail if Proxmox host unreachable
      ansible.builtin.fail:
        msg: "Cannot reach Proxmox host {{ inventory_hostname }}"
      when: ping_result.failed
    
    - name: Check Proxmox version
      ansible.builtin.command: pveversion
      register: pve_version
      changed_when: false
      tags:
        - version-check

  tasks:
    - name: Display infrastructure provisioning start
      ansible.builtin.debug:
        msg: "Starting infrastructure provisioning on {{ inventory_hostname }}"

    - name: Include proxmox role for VM provisioning
      ansible.builtin.include_role:
        name: proxmox
      vars:
        proxmox_provision_vms: true
        proxmox_provision_containers: true
      tags:
        - proxmox
        - vms
        - containers
      when: proxmox_role_enabled | default(true)

    - name: Create network bridges and VLANs
      ansible.builtin.include_tasks: tasks/network_setup.yml
      tags:
        - networking
        - vlans
      when: network_setup_enabled | default(true)

    - name: Configure storage pools
      ansible.builtin.include_tasks: tasks/storage_setup.yml
      tags:
        - storage
      when: storage_setup_enabled | default(true)

  post_tasks:
    - name: Validate provisioned infrastructure
      ansible.builtin.include_tasks: tasks/validate_infrastructure.yml
      tags:
        - validation
    
    - name: Generate provisioning report
      ansible.builtin.template:
        src: templates/provisioning_report.j2
        dest: /tmp/provisioning_report_{{ ansible_date_time.epoch }}.txt
      delegate_to: localhost
      run_once: true
      tags:
        - reporting

  handlers:
    - name: restart networking
      ansible.builtin.systemd:
        name: networking
        state: restarted
      become: true