---
# Container runtime configuration for all hosts
# These settings apply to all container deployments

# Container runtime
container_runtime: podman
container_runtime_version: "4.0"  # Minimum version

# Quadlet paths
quadlet_user_path: "{{ ansible_env.HOME }}/.config/containers/systemd"
quadlet_system_path: "/etc/containers/systemd"

# Use system quadlet for services that need to start at boot
use_system_quadlet: true

# Container storage paths
container_data_root: "{{ privatebox_base_path }}/data"
container_config_root: "{{ privatebox_base_path }}/config"
container_backup_root: "{{ privatebox_backup_path }}/containers"

# Container networking
container_network_name: privatebox-net
container_network_subnet: 172.20.0.0/16
container_network_gateway: 172.20.0.1

# Default container settings
container_restart_policy: always
container_restart_sec: 30
container_log_driver: journald
container_log_max_size: "10m"

# Resource limits (can be overridden per service)
default_memory_limit: "512M"
default_cpu_quota: "50%"

# Security defaults
container_no_new_privileges: true
container_security_label_disable: false
container_drop_capabilities:
  - ALL

# Health check defaults
health_check_interval: "30s"
health_check_timeout: "10s"
health_check_retries: 3
health_check_start_period: "60s"

# Image management
container_image_registry: "docker.io"
container_pull_policy: "missing"  # missing, always, never
container_pull_timeout: 300  # 5 minutes

# Podman-specific settings
podman_socket_path: "/run/user/{{ ansible_user_uid }}/podman/podman.sock"
podman_root_socket_path: "/run/podman/podman.sock"

# Container user mapping
container_user_namespace: "keep-id"
container_userns_size: 65536

# Volume mount options
volume_mount_options: "Z"  # SELinux relabeling

# Systemd integration
systemd_timeout_start_sec: 900  # 15 minutes for image pulls
systemd_timeout_stop_sec: 90   # 90 seconds for graceful shutdown

# Backup settings
container_backup_enabled: true
container_backup_retention_days: 7