---
# FreeBSD API Deployment Configuration for PrivateBox
# Used by freebsd-autoinstall-api.yml playbook

# Default FreeBSD VM configuration for PrivateBox environment
freebsd_api_defaults:
  # VM Resources
  vm_memory: 2048
  vm_cores: 2
  vm_disk_size: 20  # GB
  vm_storage: "local-lvm"
  network_bridge: "vmbr0"
  
  # Network Configuration - PrivateBox subnet
  vm_static_ip: "192.168.1.55"
  vm_netmask: "255.255.255.0"
  vm_gateway: "192.168.1.1"
  vm_dns1: "8.8.8.8"
  vm_dns2: "8.8.4.4"
  
  # FreeBSD System Configuration
  freebsd_version: "14.3"
  freebsd_hostname: "freebsd-privatebox"
  freebsd_interface: "vtnet0"
  freebsd_timezone: "UTC"
  freebsd_swap_size: "2G"
  
  # User Configuration
  freebsd_username: "freebsd"
  freebsd_fullname: "FreeBSD PrivateBox User"
  freebsd_shell: "/bin/sh"
  freebsd_sudo_access: true
  
  # Security Configuration for PrivateBox
  freebsd_security_hardening: true
  freebsd_ssh_security: true
  freebsd_enable_firewall: true
  freebsd_firewall_type: "simple"
  freebsd_firewall_services: "ssh"
  freebsd_firewall_allowed_ips: "192.168.1.0/24"  # PrivateBox network only
  
  # Package Installation
  freebsd_packages:
    - "bash"
    - "nano"
    - "curl"
    - "wget"
    - "git"
    - "rsync"
    - "htop"
    - "tmux"
  
  # Performance and Maintenance
  freebsd_performance_tuning: false
  freebsd_auto_updates: false
  freebsd_reboot_after_postinstall: false

# Proxmox API Configuration
# These should be set as environment variables in Semaphore
proxmox_api_config:
  host: "{{ ansible_env.PROXMOX_HOST | default('localhost') }}"
  user: "{{ ansible_env.PROXMOX_USER | default('root@pam') }}"
  password: "{{ ansible_env.PROXMOX_PASSWORD | default('') }}"
  token_id: "{{ ansible_env.PROXMOX_TOKEN_ID | default('') }}"
  token_secret: "{{ ansible_env.PROXMOX_TOKEN_SECRET | default('') }}"
  validate_certs: false
  timeout: 300

# FreeBSD ISO Configuration
freebsd_iso_config:
  version: "14.3"
  url: "https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/14.3/FreeBSD-14.3-RELEASE-amd64-disc1.iso"
  name: "FreeBSD-14.3-RELEASE-amd64-disc1.iso"
  cache_dir: "/tmp/freebsd-iso-cache"

# PrivateBox Integration Settings
privatebox_integration:
  # Network configuration for PrivateBox environment
  network_segment: "192.168.1.0/24"
  management_vm: "192.168.1.20"  # Ubuntu VM with Portainer/Semaphore
  gateway: "192.168.1.1"
  
  # Service integration
  register_with_caddy: false  # Set to true to add FreeBSD services to Caddy
  enable_monitoring: false    # Set to true to enable monitoring integration
  
  # Security settings
  ssh_key_distribution: false  # Set to true to distribute SSH keys
  centralized_logging: false   # Set to true to send logs to management VM

# VM Deployment Profiles
freebsd_vm_profiles:
  # Minimal FreeBSD VM for testing
  minimal:
    vmid: 9998
    vm_name: "freebsd-minimal"
    vm_memory: 1024
    vm_cores: 1
    vm_disk_size: 10
    freebsd_packages:
      - "bash"
      - "nano"
      - "curl"
  
  # Standard FreeBSD VM for services
  standard:
    vmid: 9997
    vm_name: "freebsd-standard"
    vm_memory: 2048
    vm_cores: 2
    vm_disk_size: 20
    freebsd_packages:
      - "bash"
      - "nano"
      - "curl"
      - "wget"
      - "git"
      - "rsync"
      - "htop"
      - "tmux"
  
  # High-performance FreeBSD VM
  performance:
    vmid: 9996
    vm_name: "freebsd-performance"
    vm_memory: 4096
    vm_cores: 4
    vm_disk_size: 40
    freebsd_performance_tuning: true
    freebsd_packages:
      - "bash"
      - "nano"
      - "curl"
      - "wget"
      - "git"
      - "rsync"
      - "htop"
      - "tmux"
      - "iperf3"
      - "netstat-nat"

# Semaphore Template Configuration
semaphore_template_config:
  name: "FreeBSD VM Autoinstall (API)"
  description: "Deploy FreeBSD 14.3 VM using Proxmox API with autoinstall"
  environment: "ServicePasswords"
  survey_enabled: true
  survey_variables:
    - variable: "vmid"
      title: "VM ID"
      type: "text"
      default: "9998"
      description: "Proxmox VM ID (must be unique)"
    - variable: "vm_name"
      title: "VM Name"
      type: "text"
      default: "freebsd-api"
      description: "Name for the FreeBSD VM"
    - variable: "vm_static_ip"
      title: "Static IP Address"
      type: "text"
      default: "192.168.1.55"
      description: "Static IP address for FreeBSD VM"
    - variable: "freebsd_hostname"
      title: "Hostname"
      type: "text"
      default: "freebsd-privatebox"
      description: "FreeBSD system hostname"
    - variable: "deployment_profile"
      title: "Deployment Profile"
      type: "select"
      default: "standard"
      options: ["minimal", "standard", "performance"]
      description: "Pre-configured resource and package profile"