---
# Network Configuration Plan for PrivateBox
# This file contains the planned network architecture with VLANs
# It will be populated by the plan-network.yml playbook during Phase 2

# VLAN Configuration
vlan_configuration:
  # Bridge to use for VLAN-aware networking
  vlan_bridge: vmbr0  # Will be auto-detected or configured
  
  # VLAN IDs - will be adjusted if conflicts detected
  vlan_ids:
    management: 10   # Management network for infrastructure
    services: 20     # Services network (AdGuard, Unbound, etc.)
    lan: 30         # Regular LAN for trusted devices
    iot: 40         # IoT network for untrusted devices

# Network Subnets
network_subnets:
  management: "10.0.10.0/24"    # VLAN 10
  services: "10.0.20.0/24"      # VLAN 20
  lan: "10.0.30.0/24"          # VLAN 30
  iot: "10.0.40.0/24"          # VLAN 40

# IP Address Assignments
ip_assignments:
  # OPNsense firewall addresses
  opnsense:
    wan: "dhcp"                 # WAN gets DHCP from ISP
    management: "10.0.10.1"     # Management VLAN gateway
    services: "10.0.20.1"       # Services VLAN gateway
    lan: "10.0.30.1"           # LAN VLAN gateway
    iot: "10.0.40.1"           # IoT VLAN gateway
  
  # Management VM (current Ubuntu management host)
  management_vm:
    current: "{{ ansible_default_ipv4.address | default('192.168.1.21') }}"
    future: "10.0.20.21"        # Will move to services VLAN
  
  # Service IP addresses
  services:
    adguard:
      primary: "10.0.20.21"     # Primary DNS (on management VM)
      secondary: "10.0.20.22"   # Secondary DNS (future)
    unbound: "10.0.20.23"       # Recursive DNS resolver
    semaphore: "10.0.20.21"     # Ansible UI (on management VM)
    portainer: "10.0.20.21"     # Container UI (on management VM)

# DHCP Ranges
dhcp_ranges:
  lan:
    start: "10.0.30.100"
    end: "10.0.30.200"
    dns_servers:
      - "10.0.20.21"  # Primary AdGuard
      - "10.0.20.22"  # Secondary AdGuard
  iot:
    start: "10.0.40.100"
    end: "10.0.40.200"
    dns_servers:
      - "10.0.20.21"  # Primary AdGuard
      - "10.0.20.22"  # Secondary AdGuard

# Firewall Rules Summary (high-level)
firewall_rules:
  # These will be detailed in Phase 2 planning
  wan_to_internal: "block all except established"
  lan_to_services: "allow DNS, block management"
  iot_to_services: "allow DNS only"
  services_to_wan: "allow outbound"
  management_access: "restricted to specific IPs"

# Migration Plan
migration_phases:
  phase_1: "Deploy OPNsense with initial config"
  phase_2: "Configure VLANs on Proxmox"
  phase_3: "Move management VM to services VLAN"
  phase_4: "Migrate existing services"
  phase_5: "Move client devices to appropriate VLANs"
  phase_6: "Remove flat network access"

# Placeholder values - will be populated by discovery
discovered_values:
  proxmox_bridges: []
  vlan_capable_bridges: []
  existing_vlans: []
  available_resources: {}