---
# OPNsense Configuration Variables
# This file defines the configuration for OPNsense with 4 VLANs as per Phase 3 implementation

# System Configuration
opnsense_version: "24.7"
opnsense_hostname: "opnsense"
domain_name: "privatebox.local"
timezone: "{{ lookup('file', '/etc/timezone', errors='ignore') | default('UTC') }}"
language: "en_US"
serial_speed: "115200"

# Network Interfaces (discovered dynamically, but defaults provided)
wan_interface: "vtnet0"
lan_interface: "vtnet1"  # This will be the VLAN trunk interface

# WAN Configuration
wan_ip: "dhcp"  # Set to specific IP or "dhcp"
wan_subnet: "24"
wan_gateway: ""  # Will be filled by DHCP or set manually
wan_monitor_ip: "1.1.1.1"  # For gateway monitoring

# DNS Configuration
dns_servers:
  - "1.1.1.1"      # Cloudflare
  - "9.9.9.9"      # Quad9
  - "8.8.8.8"      # Google DNS (fallback)

# NTP Configuration
ntp_servers: "0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org"

# Access Configuration
webgui_port: "443"
ssh_port: "22"
ssh_authorized_keys: "{{ lookup('file', '/home/ubuntuadmin/.ssh/id_rsa.pub', errors='ignore') | default('') }}"

# API Configuration
api_key: "{{ lookup('password', '/tmp/opnsense-api-key chars=ascii_letters,digits length=32') }}"
api_secret: "{{ lookup('password', '/tmp/opnsense-api-secret chars=ascii_letters,digits length=64') }}"

# VLAN Configuration
# Based on Phase 2 network design

# Management VLAN (10)
management_vlan:
  name: "Management"
  tag: 10
  ip: "10.0.10.1"
  network: "10.0.10.0/24"
  subnet: "24"
  dhcp_enabled: false  # Static IPs only for infrastructure

# Services VLAN (20)
services_vlan:
  name: "Services"
  tag: 20
  ip: "10.0.20.1"
  network: "10.0.20.0/24"
  subnet: "24"
  dhcp_enabled: false  # Static IPs only for services
  # Service IPs (for reference in templates)
  adguard_ip: "10.0.20.21"
  management_vm_ip: "10.0.20.21"  # Management VM will be migrated here
  unbound_port: "5353"  # Unbound listens on this port

# LAN VLAN (30)
lan_vlan:
  name: "LAN"
  tag: 30
  ip: "10.0.30.1"
  network: "10.0.30.0/24"
  subnet: "24"
  dhcp_enabled: true
  dhcp_start: "10.0.30.100"
  dhcp_end: "10.0.30.200"
  domain: "{{ domain_name }}"

# IoT VLAN (40)
iot_vlan:
  name: "IoT"
  tag: 40
  ip: "10.0.40.1"
  network: "10.0.40.0/24"
  subnet: "24"
  dhcp_enabled: true
  dhcp_start: "10.0.40.100"
  dhcp_end: "10.0.40.200"
  domain: "{{ domain_name }}"

# Firewall Configuration
firewall_default_policy: "deny"  # Default deny all inter-VLAN traffic
firewall_log_default_deny: true
firewall_log_sample_rate: 10  # Log 1 in 10 denied packets

# Rate Limiting Configuration
rate_limits:
  dns:
    rate: "100/sec"
    burst: 150
    action: "log+accept"
  ssh:
    rate: "5/min"
    burst: 5
    action: "drop"
  https:
    rate: "50/sec"
    burst: 50
    action: "log+accept"

# Backup Configuration
backup_enabled: true
backup_dir: "/opt/privatebox/backups/opnsense"
backup_retention_days: 30
backup_schedule: "0 2 * * *"  # 2 AM daily

# VM Configuration (for Proxmox deployment)
opnsense_vm:
  vmid: 100
  name: "opnsense"
  memory: 4096
  cores: 2
  cpu: "host"
  disk_size: "32G"
  storage: "local-lvm"  # Will be discovered dynamically
  onboot: true
  qemu_agent: true

# ISO/Image Configuration
opnsense_image:
  url: "https://mirror.dns-root.de/opnsense/releases/24.7/OPNsense-24.7-vm-amd64.qcow2"
  checksum_url: "https://mirror.dns-root.de/opnsense/releases/24.7/OPNsense-24.7-checksums-amd64.txt"
  checksum_type: "sha256"