---
# PrivateBox Service Registry
# This file defines all services that will be proxied through Caddy
# Used by caddy-alpine-install.yml to generate the Caddyfile

privatebox_services:
  # AdGuard Home - DNS-level ad blocking
  - name: adguard
    backend_host: "192.168.1.20"  # Ubuntu VM
    backend_port: 8080
    domain: adguard.lan
    description: "AdGuard Home - Network-wide ads & trackers blocking"
    health_endpoint: /
    health_status: 2xx
    # Optional: Add public domain for external access
    # public_domain: adguard.example.com
    
  # Semaphore - Ansible UI
  - name: semaphore
    backend_host: "192.168.1.20"  # Ubuntu VM
    backend_port: 3000
    domain: semaphore.lan
    description: "Semaphore - Modern UI for Ansible"
    health_endpoint: /api/ping
    health_status: 2xx
    
  # Portainer - Container Management
  - name: portainer
    backend_host: "192.168.1.20"  # Ubuntu VM
    backend_port: 9000
    domain: portainer.lan
    description: "Portainer - Container Management Platform"
    health_endpoint: /
    health_status: 2xx
    # Portainer needs WebSocket support (handled in Caddyfile template)
    
  # Future services can be added here
  # Example:
  # - name: pihole
  #   backend_host: "192.168.1.20"
  #   backend_port: 8081
  #   domain: pihole.lan
  #   public_domain: pihole.example.com  # Optional
  #   description: "Pi-hole - Network-wide Ad Blocking"
  #   health_endpoint: /admin/
  #   health_status: 2xx
  #   custom_headers:  # Optional custom headers
  #     X-Custom-Header: "value"
  #   allow_framing: true  # Allow iframe embedding if needed

# Global backend configuration
# Can be overridden per-service
backend_host: "192.168.1.20"  # Default Ubuntu VM IP

# Certificate configuration for public domains
# Used when public_domain is specified for a service
certificate_config:
  # For Let's Encrypt with Cloudflare DNS challenge
  # Set CLOUDFLARE_API_TOKEN environment variable on Alpine VM
  dns_provider: cloudflare
  
  # Alternative: Use HTTP challenge (requires port 80 open)
  # challenge_type: http
  
  # Email for Let's Encrypt notifications
  # email: admin@example.com