---
# handlers file for semaphore

- name: restart semaphore
  community.docker.docker_container:
    name: "{{ semaphore_container_name }}"
    state: started
    restart: true
  become: true

- name: backup semaphore
  ansible.builtin.include_tasks: backup.yml
  when: semaphore_backup_enabled | bool