---
# handlers file for security_hardening

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart auditd
  ansible.builtin.command: service auditd restart
  # Note: auditd cannot be restarted using systemctl

- name: restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: update grub
  ansible.builtin.command: update-grub
  when: ansible_os_family == "Debian"