---
# Markdown linting configuration

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 150
  heading_line_length: 100
  code_block_line_length: 150

# Heading style
MD003:
  style: "atx"

# Unordered list style
MD004:
  style: "dash"

# Ordered list item prefix
MD029:
  style: "ordered"

# Code block style
MD046:
  style: "fenced"

# Disable some rules
MD033: false  # Allow inline HTML
MD034: false  # Allow bare URLs
MD041: false  # First line doesn't need to be heading in all files