# FreeBSD API Environment Variables Example
# Copy this to your Semaphore environment configuration

# Required: Proxmox Connection (choose one authentication method)

# Method 1: API Token Authentication (Recommended)
PROXMOX_HOST: "192.168.1.10"
PROXMOX_USER: "root@pam"  
PROXMOX_TOKEN_ID: "automation-token"
PROXMOX_TOKEN_SECRET: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Method 2: Password Authentication (Alternative)
# PROXMOX_HOST: "192.168.1.10"
# PROXMOX_USER: "root@pam"
# PROXMOX_PASSWORD: "your-proxmox-root-password"

# Optional: Service Password (defaults to 'privatebox123')
SERVICES_PASSWORD: "your-secure-password-here"

# Optional: Advanced Configuration
# PROXMOX_VALIDATE_CERTS: "false"  # Set to true in production
# PROXMOX_TIMEOUT: "300"           # API timeout in seconds

# Instructions for Semaphore:
# 1. Go to Project Settings → Environment Variables
# 2. Create new environment called "ProxmoxAPI"
# 3. Add the variables above with your actual values
# 4. Select this environment when running FreeBSD API playbook

# To create API tokens in Proxmox:
# 1. Web UI: Datacenter → Permissions → API Tokens → Add
# 2. CLI: pveum user token add root@pam automation-token --privsep=0