---
# Homer Dashboard Configuration Update
# Deploys new config from repo and restarts service

- name: "Homer Update: Deploy New Configuration"
  hosts: privatebox-management
  gather_facts: no
  vars:
    config_dir: "/opt/homer"
    credentials_dir: "/opt/privatebox/credentials"

    # Template variables for Homer config
    custom_domain: "lan"
    headplane_api_key: "{{ lookup('file', credentials_dir + '/headplane-api-key.txt', errors='ignore') | default('', true) }}"

  tasks:
    - name: Deploy updated Homer configuration
      template:
        src: ../../templates/homer/config.yml.j2
        dest: "{{ config_dir }}/config.yml"
        owner: root
        group: root
        mode: '0644'
      register: config_updated

    - name: Deploy updated Homer icons
      copy:
        src: ../../templates/homer/tools/
        dest: "{{ config_dir }}/tools/"
        owner: root
        group: root
        mode: '0644'
        directory_mode: '0755'
      register: icons_updated

    - name: Restart Homer if config or icons changed
      systemd:
        name: homer.service
        state: restarted
      when: config_updated.changed or icons_updated.changed

    - name: Display update status
      debug:
        msg: "Homer dashboard {{ 'restarted with updates' if (config_updated.changed or icons_updated.changed) else 'already up to date' }}"