---
# Homer Dashboard Configuration Update
# Deploys new config from repo and restarts service

- name: "Homer Update: Deploy New Configuration"
  hosts: container-host
  gather_facts: no
  vars:
    config_dir: "/opt/homer"

  tasks:
    - name: Deploy updated Homer configuration
      copy:
        src: ../../templates/homer/config.yml
        dest: "{{ config_dir }}/config.yml"
        owner: root
        group: root
        mode: '0644'
      register: config_updated

    - name: Restart Homer if config changed
      systemd:
        name: homer.service
        state: restarted
      when: config_updated.changed

    - name: Display update status
      debug:
        msg: "Homer dashboard {{ 'restarted with new configuration' if config_updated.changed else 'already up to date' }}"