---
- name: "OPNsense: Stage 1 - Create FreeBSD VM"
  hosts: proxmox
  gather_facts: true
  
  vars:
    service_name: "OPNsense Firewall"
    service_description: "FreeBSD VM for OPNsense conversion"
    service_tag: "opnsense"
    
    # VM Configuration
    vmid: 963
    vm_name: "opnsense-firewall"
    vm_memory: 4096
    vm_cores: 2
    vm_disk_size: "32G"
    vm_storage: "local-lvm"
    wan_bridge: "vmbr0"
    lan_bridge: "vmbr1"
    # FreeBSD Image Configuration
    freebsd_version: "14.3"
    freebsd_image_url: "https://download.freebsd.org/releases/VM-IMAGES/14.3-RELEASE/amd64/Latest/FreeBSD-14.3-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz"
    freebsd_image_cache: "/var/lib/vz/template/cache"
    freebsd_image_name: "FreeBSD-14.3-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2"
    freebsd_image_xz: "{{ freebsd_image_name }}.xz"
    
    # Output files
    stage1_artifact_dir: "/var/lib/vz/privatebox"
    stage1_artifact_file: "{{ stage1_artifact_dir }}/opnsense-stage1.json"
    
    # Cloud-init configuration (use FreeBSD defaults for both stages)
    cloud_init_snippet: "opnsense-{{ vmid }}.yml"
    freebsd_username: "freebsd"
    freebsd_password: "freebsd"

  tasks:
    # Pre-flight checks
    - name: "{{ service_name }} - Pre-flight validation"
      tags: [opnsense, preflight]
      block:
        - name: Check if we're running on Proxmox host
          command: which qm
          register: qm_check
          changed_when: false
          failed_when: qm_check.rc != 0
          
        - name: Verify network bridges exist
          command: ip link show {{ item }}
          register: bridge_check
          changed_when: false
          failed_when: bridge_check.rc != 0
          loop:
            - "{{ wan_bridge }}"
            - "{{ lan_bridge }}"
            
        - name: Check if VM ID {{ vmid }} already exists
          command: qm status {{ vmid }}
          register: vm_exists
          changed_when: false
          failed_when: false
          
        - name: Destroy existing VM if present
          when: vm_exists.rc == 0
          block:
            - name: Stop VM {{ vmid }} if running
              command: qm stop {{ vmid }}
              register: vm_stop
              failed_when: false
              
            - name: Wait for VM to stop
              command: qm status {{ vmid }}
              register: vm_status
              until: "'stopped' in vm_status.stdout"
              retries: 30
              delay: 2
              when: vm_stop.rc == 0
              
            - name: Destroy VM {{ vmid }}
              command: qm destroy {{ vmid }} --purge
              
            - name: Confirm VM destroyed
              command: qm status {{ vmid }}
              register: destroy_check
              failed_when: destroy_check.rc == 0

    # FreeBSD image download and preparation
    - name: "{{ service_name }} - FreeBSD image preparation"
      tags: [opnsense, image]
      block:
        - name: Create cache directory
          file:
            path: "{{ freebsd_image_cache }}"
            state: directory
            mode: '0755'
            
        - name: Check if FreeBSD image already exists
          stat:
            path: "{{ freebsd_image_cache }}/{{ freebsd_image_name }}"
          register: freebsd_image_stat
          
        - name: Download FreeBSD image if not cached
          when: not freebsd_image_stat.stat.exists
          block:
            - name: Download FreeBSD .xz image
              get_url:
                url: "{{ freebsd_image_url }}"
                dest: "{{ freebsd_image_cache }}/{{ freebsd_image_xz }}"
                mode: '0644'
                timeout: 300
              register: download_result
              
            - name: Extract FreeBSD image from .xz
              command: xz -d "{{ freebsd_image_cache }}/{{ freebsd_image_xz }}"
              when: download_result.changed
              
        - name: Verify FreeBSD image exists
          stat:
            path: "{{ freebsd_image_cache }}/{{ freebsd_image_name }}"
          register: image_verify
          failed_when: not image_verify.stat.exists
          
        - name: Display image info
          debug:
            msg: "FreeBSD image ready: {{ freebsd_image_cache }}/{{ freebsd_image_name }}"

    # Ensure dependencies on Proxmox host
    - name: "{{ service_name }} - Install dependencies on Proxmox"
      tags: [opnsense, deps]
      block:
        - name: Update apt cache
          apt:
            update_cache: true
          when: ansible_facts['pkg_mgr'] == 'apt'

        - name: Install required tools (arp-scan, sshpass)
          apt:
            name:
              - arp-scan
              - sshpass
            state: present
          when: ansible_facts['pkg_mgr'] == 'apt'

    # Cloud-init minimal test
    - name: "{{ service_name }} - Cloud-init test configuration"
      tags: [opnsense, cloudinit]
      block:
        - name: Create snippets directory
          file:
            path: /var/lib/vz/snippets
            state: directory
            mode: '0755'
            
        - name: Enable snippets on local storage
          command: pvesm set local --content vztmpl,iso,backup,snippets
          failed_when: false
          
        - name: Generate password hash for FreeBSD user
          shell: openssl passwd -6 "{{ freebsd_password }}"
          register: password_hash
          changed_when: false
          no_log: true
          
        - name: Create cloud-init snippet for user creation
          copy:
            content: |
              #cloud-config
              hostname: freebsd-temp
              users:
                - name: {{ freebsd_username }}
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  passwd: {{ password_hash.stdout }}
                  shell: /bin/sh
            dest: "/var/lib/vz/snippets/{{ cloud_init_snippet }}"
            mode: '0644'

    # VM creation
    - name: "{{ service_name }} - VM creation"
      tags: [opnsense, create]
      block:
        - name: Create VM {{ vmid }}
          command: >
            qm create {{ vmid }}
            --name "{{ vm_name }}"
            --memory {{ vm_memory }}
            --cores {{ vm_cores }}
            --net0 virtio,bridge={{ wan_bridge }}
            --net1 virtio,bridge={{ lan_bridge }}
            --serial0 socket
            --vga serial0
            --ostype other
          register: vm_create
          
        - name: Import FreeBSD disk image
          command: >
            qm importdisk {{ vmid }} 
            "{{ freebsd_image_cache }}/{{ freebsd_image_name }}" 
            {{ vm_storage }}
          register: disk_import
          
        - name: Configure VM disk (no ipconfig0 - DHCP default)
          command: >
            qm set {{ vmid }}
            --virtio0 {{ vm_storage }}:vm-{{ vmid }}-disk-0
            --boot c
            --bootdisk virtio0
            
        - name: Resize disk to {{ vm_disk_size }}
          command: qm resize {{ vmid }} virtio0 {{ vm_disk_size }}
          
        - name: Add cloud-init drive
          command: qm set {{ vmid }} --ide2 {{ vm_storage }}:cloudinit
          
        - name: Configure cloud-init with custom user data (no network config)
          command: >
            qm set {{ vmid }}
            --cicustom "user=local:snippets/{{ cloud_init_snippet }}"

    # VM startup and IP discovery
    - name: "{{ service_name }} - VM startup and IP discovery"
      tags: [opnsense, start]
      block:
        - name: Start VM {{ vmid }}
          command: qm start {{ vmid }}
          
        - name: Wait for VM to start
          command: qm status {{ vmid }}
          register: vm_status_check
          until: "'running' in vm_status_check.stdout"
          retries: 30
          delay: 2
          
        - name: Extract MAC address from VM config
          shell: qm config {{ vmid }} | grep net0 | sed -E 's/.*virtio=([^,]+).*/\1/'
          register: vm_mac_result
          changed_when: false
          
        - name: Set MAC address fact
          set_fact:
            vm_mac: "{{ vm_mac_result.stdout }}"
            
        - name: Debug MAC address
          debug:
            msg: "VM MAC address: {{ vm_mac }}"

        - name: Determine WAN bridge IPv4 CIDR (if any)
          shell: |
            ip -4 addr show dev {{ wan_bridge }} | awk '/inet / {print $2; exit}'
          register: wan_cidr
          changed_when: false

        - name: Discover VM IP via arp-scan on {{ wan_bridge }} (max 4 minutes)
          shell: |
            MAC="{{ vm_mac | lower }}"
            IFACE="{{ wan_bridge }}"
            CIDR="{{ wan_cidr.stdout | trim }}"
            if [ -n "$CIDR" ]; then
              OUT=$(arp-scan --interface="$IFACE" "$CIDR" 2>/dev/null | awk -v mac="$MAC" 'tolower($2)==mac {print $1; exit}')
            else
              OUT=$(arp-scan --interface="$IFACE" --localnet 2>/dev/null | awk -v mac="$MAC" 'tolower($2)==mac {print $1; exit}')
            fi
            if [ -z "$OUT" ]; then
              # Fallback to neighbor/arp cache
              OUT=$(ip neighbor show dev "$IFACE" | awk -v mac="$MAC" 'tolower($5)==mac {print $1; exit}')
            fi
            echo -n "$OUT"
          register: vm_ip_result
          changed_when: false
          retries: 48
          delay: 5
          until: vm_ip_result.stdout != ""

        - name: Set VM IP fact
          set_fact:
            vm_ip: "{{ vm_ip_result.stdout }}"

        - name: Debug discovered IP
          debug:
            msg: "Discovered VM IP: {{ vm_ip }}"

        - name: Wait for SSH port 22 to be open (max 4 minutes)
          wait_for:
            host: "{{ vm_ip }}"
            port: 22
            timeout: 240

        - name: Test SSH access with FreeBSD user
          shell: |
            sshpass -p '{{ freebsd_password }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 \
              {{ freebsd_username }}@{{ vm_ip }} 'echo "SSH SUCCESS"; uname -a'
          register: ssh_test
          changed_when: false

        - name: Fail if SSH test failed
          fail:
            msg: "Stage 1 failed: SSH to {{ vm_ip }} with {{ freebsd_username }}/{{ freebsd_password }} did not succeed"
          when: ssh_test.rc != 0

        - name: Ensure artifact directory exists
          file:
            path: "{{ stage1_artifact_dir }}"
            state: directory
            mode: '0755'

        - name: Write Stage 1 JSON artifact
          copy:
            content: |
              {
                "status": "complete",
                "vmid": {{ vmid }},
                "name": "{{ vm_name }}",
                "wan_bridge": "{{ wan_bridge }}",
                "lan_bridge": "{{ lan_bridge }}",
                "mac": "{{ vm_mac }}",
                "ip": "{{ vm_ip }}",
                "ssh_user": "{{ freebsd_username }}",
                "timestamp": "{{ ansible_date_time.iso8601 }}"
              }
            dest: "{{ stage1_artifact_file }}"
            mode: '0644'

    # Final validation and reporting
    - name: "{{ service_name }} - Stage 1 completion report"
      tags: [opnsense, report]
      block:
        - name: Verify stage completion
          assert:
            that:
              - vm_ip is defined
              - vm_ip != ""
              - ssh_test.rc == 0
            fail_msg: "Stage 1 failed: SSH not successful"
            success_msg: "Stage 1 SUCCESS: FreeBSD VM accessible via SSH at {{ vm_ip }}"
            
        - name: Display stage 1 completion
          debug:
            msg:
              - "=========================================="
              - "{{ service_name }} - Stage 1 COMPLETE"
              - "=========================================="
              - ""
              - "VM Status: Running and accessible"
              - "VM ID: {{ vmid }}"
              - "VM Name: {{ vm_name }}"
              - "VM IP: {{ vm_ip }}"
              - "FreeBSD Version: {{ freebsd_version }}"
              - "VM MAC: {{ vm_mac }}"
              - ""
              - "Network Configuration:"
              - "- WAN Interface (vtnet0): {{ wan_bridge }} - DHCP ({{ vm_ip }})"
              - "- LAN Interface (vtnet1): {{ lan_bridge }} - Unconfigured"
              - ""
              - "Access:"
              - "- SSH Status: WORKING"
              - "- User: {{ freebsd_username }}"
              - ""
              - "Next Steps:"
              - "- Run Stage 2: opnsense-stage2-bootstrap.yml"
              - "- This will convert FreeBSD to OPNsense 25.7"
              - ""
              - "VM Management:"
              - "- Status: qm status {{ vmid }}"
              - "- Console: qm terminal {{ vmid }}"
              - "- Stop: qm stop {{ vmid }}"
              - "- Start: qm start {{ vmid }}"
              - ""
              - "Files Created:"
              - "- Stage 1 JSON: {{ stage1_artifact_file }}"
              - "=========================================="
              
        - name: Save stage 1 deployment info
          copy:
            content: |
              {{ service_name }} - Stage 1 Deployment Information
              =================================================
              Deployed: {{ ansible_date_time.iso8601 }}
              Host: {{ inventory_hostname }}
              
              VM Configuration:
              - VM ID: {{ vmid }}
              - VM Name: {{ vm_name }}
              - Memory: {{ vm_memory }} MB
              - Cores: {{ vm_cores }}
              - Disk: {{ vm_disk_size }}
              - Storage: {{ vm_storage }}
              
              Network Configuration:
              - WAN Bridge: {{ wan_bridge }} (vtnet0)
              - LAN Bridge: {{ lan_bridge }} (vtnet1)
              - VM IP: {{ vm_ip }}
              - VM MAC: {{ vm_mac }}
              
              FreeBSD Configuration:
              - Version: {{ freebsd_version }}
              - Image: {{ freebsd_image_name }}
              - User: {{ freebsd_username }}
              
              Status: Ready for Stage 2 OPNsense bootstrap
              
              Next Command:
              ansible-playbook -i inventory opnsense-stage2-bootstrap.yml
            dest: "/tmp/opnsense-stage1-deployment-info.txt"
            mode: '0644'
