---
# Meta file for proxmox role

galaxy_info:
  author: PrivateBox Team
  description: Ansible role for managing Proxmox VMs and containers
  company: PrivateBox
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  
  galaxy_tags:
    - proxmox
    - virtualization
    - vm
    - container
    - kvm
    - infrastructure
    - cloud
    - homelab
    - privatebox

dependencies: []
  # List any roles that this role depends on
  # - role: common
  #   when: proxmox_install_dependencies | default(true)

collections:
  - community.general
  # The community.general collection provides the proxmox modules:
  # - proxmox_kvm: Manage Proxmox VMs
  # - proxmox_storage_info: Get storage information
  # - proxmox_snap: Manage VM snapshots
  # - proxmox_template: Download templates and ISOs
  # - proxmox_disk: Manage VM disks (may require newer versions)

# Role-specific variables that should be defined
role_variables:
  required:
    - proxmox_api_host: "Proxmox API hostname or IP"
    - proxmox_api_user: "API username (e.g., root@pam)"
    - proxmox_api_password: "API password (or use token)"
  optional:
    - proxmox_api_token_id: "API token ID (alternative to password)"
    - proxmox_api_token_secret: "API token secret"
    - proxmox_operation: "Operation to perform (create_vm, configure_network, manage_storage)"
    - proxmox_vm_name: "Name of the VM to create"
    - proxmox_vm_vmid: "VM ID number"
    - proxmox_vm_node: "Proxmox node name"

# Example playbook usage
example_playbook: |
  ---
  - name: Create VMs on Proxmox
    hosts: localhost
    gather_facts: false
    tasks:
      - name: Create OPNsense firewall VM
        include_role:
          name: proxmox
        vars:
          proxmox_operation: create_vm
          proxmox_api_host: "192.168.1.100"
          proxmox_api_user: "root@pam"
          proxmox_api_password: "{{ vault_proxmox_password }}"
          proxmox_vm_name: "opnsense-fw01"
          proxmox_vm_vmid: 100
          proxmox_vm_node: "pve01"
          proxmox_vm_cores: 2
          proxmox_vm_memory: 4096
          proxmox_vm_disks:
            scsi0: "local-lvm:32,format=raw"
          proxmox_vm_networks:
            net0: "virtio,bridge=vmbr0,firewall=1"
            net1: "virtio,bridge=vmbr1,firewall=1"