---
# Base configuration sub-role defaults

# API user creation
opnsense_create_api_user: false
opnsense_ansible_password: "{{ vault_opnsense_ansible_password | default('changeme') }}"
opnsense_api_credentials_file: "/tmp/opnsense_api_creds.txt"

# Initial admin password (should be vaulted)
opnsense_admin_password: "{{ vault_opnsense_admin_password | default('opnsense') }}"

# Connection retry settings
opnsense_api_retries: 30
opnsense_api_delay: 10