---
# Development inventory for PrivateBox Ansible automation
# This inventory is used for testing and development purposes

all:
  children:
    privatebox:
      hosts:
        privatebox-dev:
          ansible_host: 192.168.1.100  # Update with actual VM IP after bootstrap
          ansible_user: privatebox
          ansible_become: true
          ansible_become_method: sudo
          # SSH key managed by Semaphore
          ansible_ssh_private_key_file: /root/.credentials/semaphore_ansible_key
          
          # Custom variables for this host
          environment: development
          enable_debug: true
          
    # Future group for multiple PrivateBox instances
    privatebox_cluster:
      children:
        privatebox:
      vars:
        cluster_enabled: false
        
# Global variables for development environment
  vars:
    # Development-specific settings
    container_pull_policy: always  # Always pull latest images in dev
    enable_testing_features: true
    log_level: debug
    
    # Override production defaults for development
    adguard_web_port: 8081  # Different port to avoid conflicts
    adguard_setup_port: 3002  # Avoid conflict with production