all:
  children:
    proxmox:
      hosts:
        proxmox-dev:
          ansible_host: 192.168.1.100
          proxmox_node: pve-dev
          
    network_services:
      hosts:
        opnsense:
          ansible_host: 10.10.20.1
          ansible_user: root
          vm_id: 101
          
        unbound:
          ansible_host: 10.10.10.5
          container_id: 102
          
        adguard:
          ansible_host: 10.10.10.6
          container_id: 103
          
    management_services:
      hosts:
        portainer:
          ansible_host: 10.10.10.20
          container_id: 201
          
        semaphore:
          ansible_host: 10.10.10.21
          container_id: 202
          
    privacy_services:
      hosts:
        wireguard:
          ansible_host: 10.10.10.30
          container_id: 301
          
  vars:
    ansible_user: privatebox
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
