---
# Package management tasks
- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  become: yes

- name: Update package cache (RedHat/CentOS)
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
  become: yes

- name: Install OS-specific packages (Debian/Ubuntu)
  apt:
    name: "{{ common_packages_debian }}"
    state: present
  when: 
    - ansible_os_family == "Debian"
    - common_packages_debian is defined
  become: yes

- name: Install OS-specific packages (RedHat/CentOS)
  yum:
    name: "{{ common_packages_redhat }}"
    state: present
  when: 
    - ansible_os_family == "RedHat"
    - common_packages_redhat is defined
  become: yes

- name: Remove unwanted packages
  package:
    name: "{{ common_packages_remove }}"
    state: absent
  when: common_packages_remove is defined
  become: yes

- name: Install additional security packages
  package:
    name:
      - fail2ban
      - ufw
      - unattended-upgrades
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install Python packages via pip
  pip:
    name:
      - docker
      - proxmoxer
      - requests
    state: present
    executable: pip3
  when: install_python_packages | default(true)
  become: yes

- name: Autoremove unused packages (Debian/Ubuntu)
  apt:
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Clean package cache (RedHat/CentOS)
  command: yum clean all
  when: ansible_os_family == "RedHat"
  become: yes
  changed_when: true