---
# Time and timezone configuration tasks
- name: Set system timezone
  timezone:
    name: "{{ common_timezone }}"
  when: common_timezone is defined
  become: yes
  notify: restart cron

- name: Install NTP client (Debian/Ubuntu)
  apt:
    name: "{{ common_ntp_package_debian }}"
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install NTP client (RedHat/CentOS)
  yum:
    name: "{{ common_ntp_package_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: yes

- name: Configure NTP servers (systemd-timesyncd)
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: "NTP={{ common_ntp_servers | join(' ') }}"
    state: present
  when: 
    - common_ntp_servers is defined
    - ansible_service_mgr == "systemd"
  become: yes
  notify: restart systemd-timesyncd

- name: Configure NTP servers (chrony)
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: 
    - common_ntp_servers is defined
    - common_ntp_service == "chrony"
  become: yes
  notify: restart chrony

- name: Enable and start NTP service (systemd-timesyncd)
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started
    daemon_reload: yes
  when: 
    - ansible_service_mgr == "systemd"
    - common_ntp_service == "systemd-timesyncd"
  become: yes

- name: Enable and start NTP service (chrony)
  service:
    name: chrony
    enabled: yes
    state: started
  when: common_ntp_service == "chrony"
  become: yes

- name: Enable and start NTP service (ntpd)
  service:
    name: "{{ common_ntp_daemon }}"
    enabled: yes
    state: started
  when: common_ntp_service == "ntpd"
  become: yes