---
# System update tasks
- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 86400  # 24 hours
  when: ansible_os_family == "Debian"
  become: yes

- name: Update package cache (RedHat/CentOS)
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"
  become: yes

- name: Upgrade all packages (Debian/Ubuntu)
  apt:
    upgrade: "{{ common_package_upgrade_level }}"
    autoremove: yes
    autoclean: yes
  when: 
    - ansible_os_family == "Debian"
    - common_perform_system_upgrade | default(false)
  become: yes
  register: apt_upgrade_result

- name: Upgrade all packages (RedHat/CentOS)
  yum:
    name: '*'
    state: latest
    exclude: "{{ common_upgrade_exclude_packages | default([]) }}"
  when: 
    - ansible_os_family == "RedHat"
    - common_perform_system_upgrade | default(false)
  become: yes
  register: yum_upgrade_result

- name: Check if reboot is required (Debian/Ubuntu)
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == "Debian"

- name: Check if reboot is required (RedHat/CentOS)
  command: needs-restarting -r
  register: needs_restarting
  failed_when: needs_restarting.rc not in [0, 1]
  changed_when: false
  when: ansible_os_family == "RedHat"
  become: yes

- name: Display reboot requirement message
  debug:
    msg: "System reboot is required to complete updates"
  when: >
    (ansible_os_family == "Debian" and reboot_required_file.stat.exists) or
    (ansible_os_family == "RedHat" and needs_restarting.rc == 1)

- name: Reboot system if required and allowed
  reboot:
    msg: "Rebooting to complete system updates"
    reboot_timeout: "{{ common_reboot_timeout }}"
  when: >
    common_auto_reboot | default(false) and (
      (ansible_os_family == "Debian" and reboot_required_file.stat.exists) or
      (ansible_os_family == "RedHat" and needs_restarting.rc == 1)
    )
  become: yes

- name: Clean package manager cache (Debian/Ubuntu)
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Clean package manager cache (RedHat/CentOS)
  command: yum clean all
  args:
    warn: false
  when: ansible_os_family == "RedHat"
  become: yes
  changed_when: false