---
# Handlers for Unbound DNS

- name: restart unbound
  ansible.builtin.systemd:
    name: "{{ unbound_service_name }}"
    state: restarted
    daemon_reload: yes
  listen: "restart unbound"

- name: reload unbound
  ansible.builtin.systemd:
    name: "{{ unbound_service_name }}"
    state: reloaded
  listen: "reload unbound"