---
# meta file for semaphore
galaxy_info:
  author: PrivateBox Team
  description: Deploy and configure Semaphore - Modern UI for Ansible
  company: PrivateBox
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - ansible
    - ui
    - management
    - semaphore
    - automation

dependencies: []

collections:
  - community.docker
  - community.mysql
  - community.postgresql