---
# AdGuard Home container settings
adguard_container_name: adguard-home
adguard_container_image: adguard/adguardhome:latest
adguard_container_pull: true
adguard_container_state: started
adguard_container_restart_policy: unless-stopped

# Network settings
adguard_web_port: 3000
adguard_dns_port: 53
adguard_dns_port_quic: 853
adguard_dhcp_port: 67
adguard_network_mode: bridge

# Volume settings
adguard_data_path: /var/lib/adguard
adguard_config_path: "{{ adguard_data_path }}/conf"
adguard_work_path: "{{ adguard_data_path }}/work"

# Initial configuration
adguard_web_interface: "0.0.0.0"
adguard_web_port_config: 3000
adguard_dns_interface: "0.0.0.0"
adguard_dns_port_config: 53

# Upstream DNS servers (Unbound DNS)
adguard_upstream_dns:
  - "127.0.0.1:5353"  # Unbound DNS
  - "[::1]:5353"      # Unbound DNS IPv6

# Bootstrap DNS servers
adguard_bootstrap_dns:
  - "9.9.9.9"
  - "149.112.112.112"
  - "2620:fe::fe"
  - "2620:fe::9"

# DNS settings
adguard_dnssec_enabled: true
adguard_cache_size: 4194304  # 4MB
adguard_cache_ttl_min: 600
adguard_cache_ttl_max: 86400
adguard_ratelimit: 20
adguard_blocking_mode: default

# Default blocklists
adguard_blocklists:
  - name: "AdGuard DNS filter"
    url: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
    enabled: true
  - name: "AdAway Default Blocklist"
    url: "https://adaway.org/hosts.txt"
    enabled: true
  - name: "EasyList"
    url: "https://easylist.to/easylist/easylist.txt"
    enabled: true
  - name: "EasyPrivacy"
    url: "https://easylist.to/easylist/easyprivacy.txt"
    enabled: true
  - name: "Malware Domain List"
    url: "https://www.malwaredomainlist.com/hostslist/hosts.txt"
    enabled: true
  - name: "Phishing Army"
    url: "https://phishing.army/download/phishing_army_blocklist_extended.txt"
    enabled: true

# Safe browsing and parental control
adguard_safebrowsing_enabled: true
adguard_parental_enabled: false

# Query log settings
adguard_querylog_enabled: true
adguard_querylog_interval: 24h
adguard_querylog_size_memory: 1000
adguard_querylog_file_enabled: true

# Statistics settings
adguard_statistics_enabled: true
adguard_statistics_interval: 24h

# Admin interface settings
adguard_admin_username: admin
# Password should be overridden in vault
adguard_admin_password: "{{ vault_adguard_admin_password | default('changeme') }}"

# API settings for configuration
adguard_api_url: "http://localhost:{{ adguard_web_port }}"
adguard_setup_timeout: 300
adguard_setup_retries: 10
adguard_setup_delay: 3