---
# Configure cloud-init for the VM
# This task sets up cloud-init parameters for initial VM configuration

- name: Add cloud-init drive to VM
  command: >
    qm set {{ proxmox_vm_vmid }}
    --ide2 {{ proxmox_disk_storage | default('local-lvm') }}:cloudinit
  register: _cloudinit_drive_result
  changed_when: _cloudinit_drive_result.rc == 0
  when: proxmox_vm_cloud_init_enabled | default(true)

- name: Configure cloud-init user
  command: >
    qm set {{ proxmox_vm_vmid }}
    --ciuser "{{ proxmox_vm_cloud_init_user | default('ubuntu') }}"
  register: _ciuser_result
  changed_when: _ciuser_result.rc == 0
  when: 
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_user is defined

- name: Configure cloud-init password
  command: >
    qm set {{ proxmox_vm_vmid }}
    --cipassword "{{ proxmox_vm_cloud_init_password }}"
  register: _cipassword_result
  changed_when: _cipassword_result.rc == 0
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_password is defined
    - proxmox_vm_cloud_init_password | length > 0
  no_log: true  # Don't log passwords

- name: Prepare SSH keys for cloud-init
  block:
    - name: Create temporary SSH keys file
      tempfile:
        state: file
        suffix: .pub
      register: _temp_ssh_keys_file
      when: proxmox_vm_cloud_init_ssh_keys | length > 0

    - name: Write SSH keys to temporary file
      copy:
        content: "{{ proxmox_vm_cloud_init_ssh_keys | join('\n') }}"
        dest: "{{ _temp_ssh_keys_file.path }}"
        mode: '0600'
      when: _temp_ssh_keys_file is changed

    - name: Set SSH keys file path
      set_fact:
        _ssh_keys_file: "{{ _temp_ssh_keys_file.path }}"
      when: _temp_ssh_keys_file is changed
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_ssh_keys is defined
    - proxmox_vm_cloud_init_ssh_keys | length > 0

- name: Use provided SSH keys file
  set_fact:
    _ssh_keys_file: "{{ proxmox_vm_cloud_init_ssh_keys_file }}"
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_ssh_keys_file is defined
    - proxmox_vm_cloud_init_ssh_keys_file | length > 0

- name: Configure cloud-init SSH keys
  command: >
    qm set {{ proxmox_vm_vmid }}
    --sshkeys "{{ _ssh_keys_file }}"
  register: _sshkeys_result
  changed_when: _sshkeys_result.rc == 0
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - _ssh_keys_file is defined

- name: Configure cloud-init network
  command: >
    qm set {{ proxmox_vm_vmid }}
    --ipconfig0 "ip={{ proxmox_vm_cloud_init_ip | default('dhcp') }}{% if proxmox_vm_cloud_init_gw is defined and proxmox_vm_cloud_init_gw | length > 0 %},gw={{ proxmox_vm_cloud_init_gw }}{% endif %}"
  register: _ipconfig_result
  changed_when: _ipconfig_result.rc == 0
  when: proxmox_vm_cloud_init_enabled | default(true)

- name: Configure cloud-init nameserver
  command: >
    qm set {{ proxmox_vm_vmid }}
    --nameserver "{{ proxmox_vm_cloud_init_dns }}"
  register: _nameserver_result
  changed_when: _nameserver_result.rc == 0
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_dns is defined
    - proxmox_vm_cloud_init_dns | length > 0

- name: Configure cloud-init search domain
  command: >
    qm set {{ proxmox_vm_vmid }}
    --searchdomain "{{ proxmox_vm_cloud_init_domain }}"
  register: _searchdomain_result
  changed_when: _searchdomain_result.rc == 0
  when:
    - proxmox_vm_cloud_init_enabled | default(true)
    - proxmox_vm_cloud_init_domain is defined
    - proxmox_vm_cloud_init_domain | length > 0

- name: Update boot order to include cloud-init drive
  command: >
    qm set {{ proxmox_vm_vmid }}
    --boot "order=scsi0;ide2;net0"
  register: _boot_order_result
  changed_when: _boot_order_result.rc == 0
  when: proxmox_vm_cloud_init_enabled | default(true)

- name: Clean up temporary SSH keys file
  file:
    path: "{{ _temp_ssh_keys_file.path }}"
    state: absent
  when: _temp_ssh_keys_file is defined

- name: Display cloud-init configuration summary
  debug:
    msg:
      - "Cloud-init configured successfully"
      - "User: {{ proxmox_vm_cloud_init_user | default('ubuntu') }}"
      - "Network: {{ proxmox_vm_cloud_init_ip | default('dhcp') }}"
      - "{% if proxmox_vm_cloud_init_gw is defined %}Gateway: {{ proxmox_vm_cloud_init_gw }}{% endif %}"
      - "{% if proxmox_vm_cloud_init_dns is defined %}DNS: {{ proxmox_vm_cloud_init_dns }}{% endif %}"
      - "{% if proxmox_vm_cloud_init_ssh_keys is defined %}SSH Keys: {{ proxmox_vm_cloud_init_ssh_keys | length }} key(s) configured{% endif %}"
  when: proxmox_vm_cloud_init_enabled | default(true)