---
# Import cloud image as VM disk
# This task imports the downloaded cloud image as the VM's primary disk

- name: Verify cloud image is ready
  assert:
    that:
      - _cloud_image_ready is defined
      - _cloud_image_ready | bool
      - _cloud_image_path is defined
    fail_msg: "Cloud image not prepared. Run prepare_cloud_image.yml first."

- name: Import cloud image as VM disk
  command: >
    qm importdisk {{ proxmox_vm_vmid }} 
    {{ _cloud_image_path }} 
    {{ proxmox_disk_storage | default('local-lvm') }}
    --format {{ proxmox_vm_import_disk_format | default('qcow2') }}
  register: _import_result
  changed_when: "'Successfully imported disk' in _import_result.stdout"

- name: Display import result
  debug:
    msg: "Disk import output: {{ _import_result.stdout_lines }}"
  when: ansible_verbosity >= 1

- name: Extract imported disk name from output
  set_fact:
    _imported_disk: "{{ _import_result.stdout | regex_search('as .(unused\\d+).', '\\1') | first | default('unused0') }}"

- name: Attach imported disk to VM as scsi0
  command: >
    qm set {{ proxmox_vm_vmid }}
    --scsi0 {{ proxmox_disk_storage | default('local-lvm') }}:vm-{{ proxmox_vm_vmid }}-disk-0
  register: _attach_result
  changed_when: _attach_result.rc == 0

- name: Set boot disk
  command: >
    qm set {{ proxmox_vm_vmid }}
    --boot c --bootdisk scsi0
  register: _boot_result
  changed_when: _boot_result.rc == 0

- name: Resize disk if specified
  command: >
    qm resize {{ proxmox_vm_vmid }} scsi0 {{ proxmox_vm_import_disk_size_increase }}
  when: proxmox_vm_import_disk_size_increase is defined and proxmox_vm_import_disk_size_increase | length > 0
  register: _resize_result
  changed_when: "'successfully' in _resize_result.stdout | lower"
  failed_when: 
    - _resize_result.rc != 0
    - "'unable to shrink' not in _resize_result.stderr | lower"

- name: Set serial console for cloud-init output
  command: >
    qm set {{ proxmox_vm_vmid }}
    --serial0 socket --vga serial0
  register: _serial_result
  changed_when: _serial_result.rc == 0

- name: Display disk configuration summary
  debug:
    msg:
      - "Cloud image imported successfully"
      - "Disk attached as: scsi0"
      - "Storage: {{ proxmox_disk_storage | default('local-lvm') }}"
      - "Format: {{ proxmox_vm_import_disk_format | default('qcow2') }}"
      - "{% if _resize_result is changed %}Disk resized by: {{ proxmox_vm_import_disk_size_increase }}{% endif %}"
  when: ansible_verbosity >= 0