---
# defaults file for common

# Package management
common_packages:
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - tmux

# OS-specific packages
common_packages_debian:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3-apt

common_packages_redhat:
  - epel-release
  - python3-dnf

# Packages to remove
common_packages_remove: []

# System updates
common_perform_system_upgrade: false
common_package_upgrade_level: safe  # safe, full, dist
common_upgrade_exclude_packages: []
common_auto_reboot: false
common_reboot_timeout: 600

# User management
common_sudo_group: sudo  # 'wheel' for RedHat-based systems
common_admin_users: []
# Example user structure:
# common_admin_users:
#   - name: admin
#     groups: [sudo, docker]
#     shell: /bin/bash
#     ssh_key: "ssh-rsa AAAAB3..."
#     ssh_key_exclusive: false
#     comment: "Admin User"

# Time configuration
common_timezone: UTC
common_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

# NTP service configuration
common_ntp_service: systemd-timesyncd  # systemd-timesyncd, chrony, ntpd
common_ntp_package_debian: systemd-timesyncd
common_ntp_package_redhat: chrony
common_ntp_daemon: ntpd
common_cron_service: cron  # crond for RedHat-based systems

# SSH configuration
common_ssh_package: openssh-server
common_ssh_service: sshd  # ssh for some Debian-based systems
common_ssh_port: 22
common_ssh_permit_root_login: "no"
common_ssh_password_authentication: "no"
common_ssh_pubkey_authentication: "yes"
common_ssh_permit_empty_passwords: "no"
common_ssh_challenge_response_authentication: "no"
common_ssh_gssapi_authentication: "no"
common_ssh_x11_forwarding: "no"
common_ssh_strict_modes: "yes"
common_ssh_use_pam: "yes"
common_ssh_use_dns: "no"
common_ssh_print_motd: "no"
common_ssh_print_last_log: "yes"
common_ssh_tcp_keep_alive: "yes"
common_ssh_client_alive_interval: 300
common_ssh_client_alive_count_max: 2
common_ssh_max_auth_tries: 3
common_ssh_max_sessions: 10
common_ssh_login_grace_time: 60
common_ssh_banner: |
  ******************************************************************
  * This system is for authorized use only. All connections are   *
  * monitored and recorded. Disconnect immediately if you are not *
  * an authorized user.                                            *
  ******************************************************************

# SSH crypto settings
common_ssh_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

common_ssh_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com

common_ssh_kex_algorithms:
  - curve25519-sha256
  - curve25519-sha256@libssh.org
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group-exchange-sha256

# Firewall management
common_manage_firewall: false
