---
# Proxmox host-specific variables

# Proxmox API configuration
proxmox_api_user: root@pam
proxmox_api_host: "{{ inventory_hostname }}"
proxmox_api_validate_certs: false

# Storage configuration
proxmox_storage_default: local-lvm
proxmox_storage_iso: local
proxmox_storage_backup: local

# VM defaults
proxmox_vm_defaults:
  cores: 2
  memory: 2048
  balloon: 0
  onboot: yes
  agent: yes
  boot: order=scsi0
  scsihw: virtio-scsi-pci
  ostype: l26
  cpu: host

# Container defaults
proxmox_ct_defaults:
  cores: 1
  memory: 512
  swap: 512
  onboot: yes
  unprivileged: yes
  features: 
    - nesting=1
    - keyctl=1

# Network configuration
proxmox_network_bridge: vmbr0
proxmox_vlan_aware: true

# VLAN definitions
proxmox_vlans:
  management:
    id: 10
    name: VLAN-Management
    subnet: 10.10.10.0/24
    gateway: 10.10.10.1
  services:
    id: 20
    name: VLAN-Services
    subnet: 10.10.20.0/24
    gateway: 10.10.20.1
  iot:
    id: 30
    name: VLAN-IoT
    subnet: 10.10.30.0/24
    gateway: 10.10.30.1
  guest:
    id: 40
    name: VLAN-Guest
    subnet: 10.10.40.0/24
    gateway: 10.10.40.1
  lan:
    id: 50
    name: VLAN-LAN
    subnet: 10.10.50.0/24
    gateway: 10.10.50.1

# Cluster settings (if applicable)
proxmox_cluster_enabled: false
proxmox_cluster_name: privatebox-cluster

# Resource pools
proxmox_pools:
  - name: production
    comment: "Production services"
  - name: development
    comment: "Development and testing"

# Backup configuration
proxmox_backup_enabled: true
proxmox_backup_schedule: "0 2 * * *"  # 2 AM daily
proxmox_backup_mode: snapshot
proxmox_backup_compress: zstd
proxmox_backup_retention: 7

# ZFS settings (if applicable)
proxmox_zfs_enabled: false
proxmox_zfs_arc_max: ""  # Leave empty for auto
proxmox_zfs_compression: lz4

# Monitoring
proxmox_metrics_enabled: true
proxmox_metrics_server: ""
proxmox_metrics_port: 8086

# Security
proxmox_firewall_enabled: true
proxmox_fail2ban_enabled: true

# Updates
proxmox_enterprise_repo: false
proxmox_no_subscription_warning: true