---
# Ubuntu server and containerized services configuration

# Ubuntu version
ubuntu_version: "22.04"
ubuntu_server_type: "lxc"  # lxc or vm

# Container/VM specifications
ubuntu_container_cores: 2
ubuntu_container_memory: 2048
ubuntu_container_disk_size: 16
ubuntu_container_privileged: false

# Base system configuration
ubuntu_base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - python3-pip
  - python3-venv
  - git
  - vim
  - htop
  - iotop
  - net-tools
  - dnsutils
  - tcpdump
  - tmux
  - rsync
  - unzip
  - jq

# Docker configuration
docker_install: true
docker_version: "24.0"
docker_compose_install: true
docker_users:
  - privatebox
  - ansible

# Service-specific configurations

# AdGuard Home
adguard_home_enabled: true
adguard_home_port: 3000
adguard_home_dns_port: 53
adguard_home_version: "latest"
adguard_home_config_path: "{{ privatebox_config_path }}/adguard"
adguard_home_data_path: "{{ privatebox_data_path }}/adguard"
adguard_home_blocklists:
  - name: "AdGuard DNS filter"
    url: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
  - name: "AdAway Default Blocklist"
    url: "https://adaway.org/hosts.txt"
  - name: "MalwareDomainList"
    url: "https://www.malwaredomainlist.com/hostslist/hosts.txt"

# Unbound DNS
unbound_enabled: true
unbound_port: 53
unbound_version: "latest"
unbound_config_path: "{{ privatebox_config_path }}/unbound"
unbound_forward_zones:
  - name: "."
    forward_addresses:
      - "10.0.20.53#5053"  # Forward to AdGuard
unbound_access_control:
  - "10.0.0.0/16 allow"
  - "127.0.0.0/8 allow"
  - "0.0.0.0/0 deny"

# Portainer
portainer_enabled: true
portainer_port: 9000
portainer_edge_port: 8000
portainer_version: "latest"
portainer_data_path: "{{ privatebox_data_path }}/portainer"
portainer_templates_enabled: true

# Semaphore
semaphore_enabled: true
semaphore_port: 3001
semaphore_version: "latest"
semaphore_db_type: "sqlite"
semaphore_config_path: "{{ privatebox_config_path }}/semaphore"
semaphore_data_path: "{{ privatebox_data_path }}/semaphore"
semaphore_ldap_enabled: false

# Wireguard UI
wireguard_ui_enabled: true
wireguard_ui_port: 5000
wireguard_ui_version: "latest"
wireguard_ui_config_path: "{{ privatebox_config_path }}/wireguard-ui"
wireguard_ui_peers_path: "{{ privatebox_config_path }}/wireguard"

# Pi-hole (alternative to AdGuard)
pihole_enabled: false
pihole_port: 8080
pihole_version: "latest"
pihole_config_path: "{{ privatebox_config_path }}/pihole"
pihole_data_path: "{{ privatebox_data_path }}/pihole"

# Nginx Proxy Manager
nginx_proxy_manager_enabled: false
nginx_proxy_manager_port: 81
nginx_proxy_manager_http_port: 80
nginx_proxy_manager_https_port: 443
nginx_proxy_manager_version: "latest"
nginx_proxy_manager_data_path: "{{ privatebox_data_path }}/nginx-proxy-manager"

# Prometheus (monitoring)
prometheus_enabled: true
prometheus_port: 9090
prometheus_version: "latest"
prometheus_config_path: "{{ privatebox_config_path }}/prometheus"
prometheus_data_path: "{{ privatebox_data_path }}/prometheus"
prometheus_retention: "15d"

# Grafana (monitoring)
grafana_enabled: true
grafana_port: 3002
grafana_version: "latest"
grafana_config_path: "{{ privatebox_config_path }}/grafana"
grafana_data_path: "{{ privatebox_data_path }}/grafana"

# Node Exporter (monitoring)
node_exporter_enabled: true
node_exporter_port: 9100
node_exporter_version: "latest"

# Service resource limits
service_resource_limits:
  adguard_home:
    memory: "512m"
    cpus: "0.5"
  unbound:
    memory: "256m"
    cpus: "0.25"
  portainer:
    memory: "512m"
    cpus: "0.5"
  semaphore:
    memory: "512m"
    cpus: "0.5"
  wireguard_ui:
    memory: "256m"
    cpus: "0.25"
  prometheus:
    memory: "1g"
    cpus: "1"
  grafana:
    memory: "512m"
    cpus: "0.5"

# Container restart policies
container_restart_policy: "unless-stopped"

# Network settings for containers
container_network_name: "privatebox"
container_network_subnet: "172.20.0.0/24"

# Logging configuration
container_logging_driver: "json-file"
container_logging_options:
  max-size: "10m"
  max-file: "3"