---
# Provision sub-role specific defaults

# Proxmox connection details
proxmox_host: "{{ groups['proxmox'][0] }}"
proxmox_node: "pve"

# Installation timeout
opnsense_install_timeout: 1800  # 30 minutes

# VM creation retries
opnsense_vm_create_retries: 3
opnsense_vm_create_delay: 10