---
galaxy_info:
  author: PrivateBox Team
  description: AdGuard Home DNS filtering service deployment
  company: PrivateBox
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - dns
    - adguard
    - security
    - privacy
    - containers
    - podman

dependencies: []