---
# Production inventory for PrivateBox Ansible automation
# This inventory is used for actual deployments

all:
  children:
    privatebox:
      hosts:
        privatebox-prod:
          ansible_host: 192.168.1.50  # Update with actual production VM IP
          ansible_user: privatebox
          ansible_become: true
          ansible_become_method: sudo
          # SSH key managed by Semaphore - no need to specify here
          
          # Custom variables for this host
          environment: production
          enable_debug: false
          
        # Add more PrivateBox instances as needed
        # privatebox-prod-2:
        #   ansible_host: 192.168.1.51
        #   ansible_user: privatebox
        #   ansible_become: true
        #   ansible_become_method: sudo
          
    # Group for multiple PrivateBox instances
    privatebox_cluster:
      children:
        privatebox:
      vars:
        cluster_enabled: false
        
# Global variables for production environment
  vars:
    # Production-specific settings
    container_pull_policy: missing  # Only pull if image doesn't exist
    enable_testing_features: false
    log_level: info
    
    # Production defaults (can be overridden in group_vars)
    adguard_web_port: 8080
    adguard_setup_port: 3001