---
# AppArmor configuration tasks

- name: Install AppArmor packages
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present

- name: Enable AppArmor at boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 security=apparmor"'
    backup: true
  register: grub_config

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  when: grub_config.changed

- name: Check AppArmor status
  ansible.builtin.command: aa-status
  register: apparmor_status
  changed_when: false

- name: Set AppArmor profiles to enforce mode
  ansible.builtin.command: aa-enforce /etc/apparmor.d/*
  changed_when: false
  failed_when: false

- name: Enable and start AppArmor service
  ansible.builtin.systemd:
    name: apparmor
    state: started
    enabled: true

- name: Display AppArmor status
  ansible.builtin.debug:
    msg: "AppArmor is active with {{ apparmor_status.stdout_lines | select('match', '.*profiles are in enforce mode.*') | first | regex_search('[0-9]+') }} profiles in enforce mode"
  when: apparmor_status.stdout_lines is defined