---
# Fail2ban configuration tasks

- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Create fail2ban configuration directory
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure fail2ban defaults
  ansible.builtin.template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart fail2ban

- name: Configure fail2ban service jails
  ansible.builtin.template:
    src: fail2ban/jail.d/service.conf.j2
    dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_services }}"
  when: item.enabled | bool
  notify: restart fail2ban

- name: Create custom fail2ban filters directory
  ansible.builtin.file:
    path: /etc/fail2ban/filter.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Enable and start fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Check fail2ban status
  ansible.builtin.command: fail2ban-client status
  register: fail2ban_status
  changed_when: false

- name: Display fail2ban status
  ansible.builtin.debug:
    var: fail2ban_status.stdout_lines