---
# Firewall configuration tasks

- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Reset UFW to defaults
  community.general.ufw:
    state: reset

- name: Set UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: "{{ firewall_default_incoming_policy }}" }
    - { direction: outgoing, policy: "{{ firewall_default_outgoing_policy }}" }

- name: Allow SSH port through firewall
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port | string }}"
    proto: tcp
    comment: "SSH access"

- name: Allow additional TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: tcp
  loop: "{{ firewall_allowed_tcp_ports }}"
  when: firewall_allowed_tcp_ports is defined and firewall_allowed_tcp_ports | length > 0

- name: Allow additional UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: udp
  loop: "{{ firewall_allowed_udp_ports }}"
  when: firewall_allowed_udp_ports is defined and firewall_allowed_udp_ports | length > 0

- name: Allow specific networks
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
  loop: "{{ firewall_allowed_networks }}"
  when: firewall_allowed_networks is defined and firewall_allowed_networks | length > 0

- name: Set UFW logging level
  community.general.ufw:
    logging: "{{ firewall_log_level }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Check UFW status
  ansible.builtin.command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Display UFW status
  ansible.builtin.debug:
    var: ufw_status.stdout_lines