---
# Kernel hardening tasks

- name: Configure sysctl settings for security
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-security-hardening.conf
  loop: "{{ sysctl_settings | dict2items }}"

- name: Create modprobe configuration directory
  ansible.builtin.file:
    path: /etc/modprobe.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Disable unnecessary kernel modules
  ansible.builtin.copy:
    content: |
      # Disable rare network protocols
      install dccp /bin/true
      install sctp /bin/true
      install rds /bin/true
      install tipc /bin/true
      
      # Disable rare filesystems
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install squashfs /bin/true
      install udf /bin/true
      
      # Disable firewire
      install firewire-core /bin/true
      blacklist firewire-core
      
      # Disable USB storage (uncomment if needed)
      # install usb-storage /bin/true
    dest: /etc/modprobe.d/security-blacklist.conf
    owner: root
    group: root
    mode: '0644'

- name: Set kernel.dmesg_restrict
  ansible.posix.sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    state: present
    reload: true

- name: Configure kernel panic behavior
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: 'kernel.panic', value: '10' }
    - { name: 'kernel.panic_on_oops', value: '1' }

- name: Apply sysctl settings immediately
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-security-hardening.conf
  changed_when: false