---
# Rootkit detection tasks

- name: Install rootkit detection tools
  ansible.builtin.package:
    name: "{{ rootkit_detection_tools }}"
    state: present

- name: Update rkhunter database
  ansible.builtin.command: rkhunter --update
  changed_when: false
  failed_when: false

- name: Configure rkhunter
  ansible.builtin.template:
    src: rkhunter/rkhunter.conf.j2
    dest: /etc/rkhunter.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Initialize rkhunter properties database
  ansible.builtin.command: rkhunter --propupd
  changed_when: false

- name: Create rkhunter cron job
  ansible.builtin.cron:
    name: "Run rkhunter daily"
    job: "/usr/bin/rkhunter --cronjob --report-warnings-only --skip-keypress"
    hour: "3"
    minute: "30"
    user: root

- name: Configure chkrootkit
  ansible.builtin.copy:
    content: |
      RUN_DAILY="true"
      RUN_DAILY_OPTS="-q"
      DIFF_MODE="true"
    dest: /etc/chkrootkit.conf
    owner: root
    group: root
    mode: '0644'

- name: Create chkrootkit cron job
  ansible.builtin.cron:
    name: "Run chkrootkit daily"
    job: "/usr/sbin/chkrootkit -q 2>&1 | grep -v 'nothing found' | mail -E -s 'chkrootkit report' root"
    hour: "4"
    minute: "0"
    user: root

- name: Run initial rootkit scan
  ansible.builtin.command: rkhunter --check --skip-keypress --report-warnings-only
  register: rkhunter_scan
  changed_when: false
  failed_when: false

- name: Display rootkit scan results
  ansible.builtin.debug:
    msg: "Initial rootkit scan completed. Check /var/log/rkhunter.log for details."