---
# System updates configuration tasks

- name: Install unattended-upgrades package
  ansible.builtin.package:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: unattended-upgrades/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Configure automatic updates schedule
  ansible.builtin.template:
    src: unattended-upgrades/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Configure apt periodic updates
  ansible.builtin.template:
    src: unattended-upgrades/10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Enable unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Run initial unattended-upgrades dry run
  ansible.builtin.command: unattended-upgrades --dry-run --debug
  register: unattended_upgrades_test
  changed_when: false
  failed_when: false

- name: Display unattended-upgrades configuration test
  ansible.builtin.debug:
    msg: "Unattended upgrades configured successfully"
  when: unattended_upgrades_test.rc == 0