---
# PrivateBox Master Site Playbook
# Orchestrates the complete deployment of PrivateBox infrastructure and services

# Import all orchestration playbooks with proper ordering and tags

# Phase 1: Infrastructure Provisioning
- name: Provision Infrastructure
  import_playbook: provisioning/provision_infrastructure.yml
  tags:
    - infrastructure
    - provisioning
    - phase1

# Phase 2: Base Services Deployment
- name: Deploy Base Services
  import_playbook: deployment/deploy_base_services.yml
  tags:
    - base
    - deployment
    - phase2

# Phase 3: Network Services Deployment
- name: Deploy Network Services
  import_playbook: deployment/deploy_network_services.yml
  tags:
    - network
    - deployment
    - phase3

# Phase 4: OPNSense Initial Configuration
- name: Configure OPNSense
  import_playbook: deployment/configure_opnsense_initial.yml
  tags:
    - opnsense
    - configuration
    - phase4

# Phase 5: Management Services Deployment
- name: Deploy Management Services
  import_playbook: deployment/deploy_management_services.yml
  tags:
    - management
    - deployment
    - phase5

# Phase 6: Final Validation
- name: Validate Complete Deployment
  import_playbook: maintenance/validate_deployment.yml
  tags:
    - validation
    - post-deployment
    - phase6

# Maintenance playbooks (not part of initial deployment)
# These can be run independently using their specific tags

# Run system maintenance
# ansible-playbook site.yml --tags maintenance-updates
- name: System Maintenance
  import_playbook: maintenance/common_vm_maintenance.yml
  tags:
    - maintenance-updates
    - never  # Prevent running during normal deployment

# Update DNS blocklists
# ansible-playbook site.yml --tags blocklist-update
- name: Update DNS Blocklists
  import_playbook: maintenance/update_blocklists.yml
  tags:
    - blocklist-update
    - never  # Prevent running during normal deployment

# Full deployment validation (can be run anytime)
# ansible-playbook site.yml --tags validate-only
- name: Validation Only
  import_playbook: maintenance/validate_deployment.yml
  tags:
    - validate-only
    - never  # Prevent running during normal deployment