---
# Optimize VM disk configuration based on storage type
# Variables required: vm_id, storage_pool

- name: Get storage type
  shell: |
    pvesm status | grep "^{{ storage_pool }}" | awk '{print $2}'
  register: storage_type
  
- name: Check if storage is SSD/NVMe
  shell: |
    # Check for SSD in multiple ways
    device=$(pvesm path {{ storage_pool }}:vm-{{ vm_id }}-disk-0 | cut -d'/' -f3)
    if [ -z "$device" ]; then
      # LVM or other storage
      device=$(lvdisplay 2>/dev/null | grep -B1 "vm-{{ vm_id }}-disk" | grep "PV Name" | awk '{print $3}' | cut -d'/' -f3)
    fi
    
    if [ -n "$device" ]; then
      # Check rotational flag (0 = SSD, 1 = HDD)
      if [ -f "/sys/block/${device}/queue/rotational" ]; then
        cat /sys/block/${device}/queue/rotational
      else
        echo "1"  # Assume HDD if can't determine
      fi
    else
      echo "1"  # Default to HDD settings
    fi
  register: is_rotational
  
- name: Determine optimal disk settings
  set_fact:
    disk_cache: >-
      {{
        'writeback' if is_rotational.stdout == '0' else 'directsync'
      }}
    disk_discard: >-
      {{
        'on' if is_rotational.stdout == '0' and storage_type.stdout in ['lvmthin', 'zfspool'] else 'ignore'
      }}
    disk_iothread: >-
      {{
        '1' if is_rotational.stdout == '0' else '0'
      }}
    disk_aio: >-
      {{
        'io_uring' if is_rotational.stdout == '0' else 'threads'
      }}
      
- name: Apply optimized disk settings
  shell: |
    qm set {{ vm_id }} \
      --scsi0 {{ storage_pool }}:vm-{{ vm_id }}-disk-0,cache={{ disk_cache }},discard={{ disk_discard }},iothread={{ disk_iothread }},aio={{ disk_aio }}
      
- name: Enable SSD-specific optimizations
  shell: |
    qm set {{ vm_id }} --scsihw virtio-scsi-single
  when: is_rotational.stdout == '0'
  
- name: Configure disk I/O limits for HDD
  shell: |
    # Limit IOPS on HDD to prevent thrashing
    qm set {{ vm_id }} \
      --scsi0 {{ storage_pool }}:vm-{{ vm_id }}-disk-0,mbps_rd=100,mbps_wr=100,iops_rd=500,iops_wr=500
  when: is_rotational.stdout == '1'
  
- name: Display disk optimization results
  debug:
    msg:
      - "Storage Type: {{ storage_type.stdout }}"
      - "Disk Type: {{ 'SSD/NVMe' if is_rotational.stdout == '0' else 'HDD' }}"
      - "Cache Mode: {{ disk_cache }}"
      - "Discard: {{ disk_discard }}"
      - "I/O Thread: {{ 'Enabled' if disk_iothread == '1' else 'Disabled' }}"
      - "AIO Mode: {{ disk_aio }}"