---
# Update AdGuard Home blocklists

- name: Login to AdGuard Home
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/login"
    method: POST
    body_format: json
    body:
      name: "{{ adguard_admin_username }}"
      password: "{{ adguard_admin_password }}"
    status_code: 200
  register: login_result

- name: Set authentication cookie
  ansible.builtin.set_fact:
    adguard_auth_cookie: "{{ login_result.cookies_string }}"

- name: Get current filter list
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/filtering/status"
    method: GET
    headers:
      Cookie: "{{ adguard_auth_cookie }}"
    status_code: 200
  register: current_filters

- name: Extract current filter URLs
  ansible.builtin.set_fact:
    current_filter_urls: "{{ current_filters.json.filters | default([]) | map(attribute='url') | list }}"

- name: Add new blocklists
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/filtering/add_url"
    method: POST
    headers:
      Cookie: "{{ adguard_auth_cookie }}"
    body_format: json
    body:
      name: "{{ item.name }}"
      url: "{{ item.url }}"
      enabled: "{{ item.enabled }}"
    status_code: 200
  loop: "{{ adguard_blocklists }}"
  when: 
    - adguard_blocklists is defined
    - item.url not in current_filter_urls

- name: Update existing blocklists status
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/filtering/set_url"
    method: POST
    headers:
      Cookie: "{{ adguard_auth_cookie }}"
    body_format: json
    body:
      url: "{{ item.url }}"
      data:
        enabled: "{{ item.enabled }}"
        name: "{{ item.name }}"
        url: "{{ item.url }}"
    status_code: 200
  loop: "{{ adguard_blocklists }}"
  when:
    - adguard_blocklists is defined
    - item.url in current_filter_urls

- name: Refresh all blocklists
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/filtering/refresh"
    method: POST
    headers:
      Cookie: "{{ adguard_auth_cookie }}"
    body_format: json
    body:
      whitelist: false
    status_code: 200

- name: Wait for blocklist refresh to complete
  ansible.builtin.pause:
    seconds: 5

- name: Get filter refresh status
  ansible.builtin.uri:
    url: "{{ adguard_api_url }}/control/filtering/status"
    method: GET
    headers:
      Cookie: "{{ adguard_auth_cookie }}"
    status_code: 200
  register: filter_status

- name: Display blocklist update results
  ansible.builtin.debug:
    msg:
      - "Total filters: {{ filter_status.json.filters | length }}"
      - "Enabled filters: {{ filter_status.json.filters | selectattr('enabled', 'equalto', true) | list | length }}"
      - "Total rules: {{ filter_status.json.filters | sum(attribute='rules_count') }}"