---
# SSL configuration tasks for portainer

- name: Check if SSL certificates exist
  ansible.builtin.stat:
    path: "{{ item }}"
  register: ssl_cert_check
  loop:
    - "{{ portainer_ssl_cert_path }}"
    - "{{ portainer_ssl_key_path }}"

- name: Generate self-signed SSL certificate
  ansible.builtin.command: |
    openssl req -new -x509 -days 365 -nodes \
      -out "{{ portainer_ssl_cert_path }}" \
      -keyout "{{ portainer_ssl_key_path }}" \
      -subj "/C=US/ST=State/L=City/O=PrivateBox/CN={{ ansible_host }}"
  args:
    creates: "{{ portainer_ssl_cert_path }}"
  when: ssl_cert_check.results[0].stat.exists == false

- name: Set proper permissions on SSL certificates
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  loop:
    - "{{ portainer_ssl_cert_path }}"
    - "{{ portainer_ssl_key_path }}"

- name: Restart Portainer with SSL
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    image: "{{ portainer_container_image }}"
    state: started
    restart: true
    restart_policy: "{{ portainer_container_restart_policy }}"
    networks:
      - name: "{{ portainer_network_name }}"
    ports:
      - "{{ portainer_web_port }}:9443"
      - "{{ portainer_agent_port }}:8000"
    volumes:
      - "{{ portainer_docker_socket }}:/var/run/docker.sock:ro"
      - "{{ portainer_data_dir }}:/data"
      - "{{ portainer_ssl_cert_path }}:/certs/cert.pem:ro"
      - "{{ portainer_ssl_key_path }}:/certs/key.pem:ro"
    command: "--ssl --sslcert /certs/cert.pem --sslkey /certs/key.pem"
    env:
      PORTAINER_HIDE_LABELS: "{{ portainer_hide_labels | string }}"
    labels:
      service: "portainer"
      role: "management"
      managed_by: "ansible"
  become: true
  when: portainer_ssl_enabled | bool

- name: Display SSL-enabled Portainer access information
  ansible.builtin.debug:
    msg:
      - "Portainer is now running with SSL enabled!"
      - "Access URL: https://{{ ansible_host }}:{{ portainer_web_port }}"
      - "Note: Self-signed certificate warning is expected"
  when: portainer_ssl_enabled | bool