---
# Agent deployment tasks for portainer

- name: Pull Portainer Agent image
  community.docker.docker_image:
    name: "{{ portainer_agent_image }}"
    source: pull
    state: present
  become: true

- name: Deploy Portainer Agent container
  community.docker.docker_container:
    name: "{{ portainer_agent_container_name }}"
    image: "{{ portainer_agent_image }}"
    state: started
    restart_policy: "{{ portainer_container_restart_policy }}"
    networks:
      - name: "{{ portainer_network_name }}"
    ports:
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    env:
      AGENT_CLUSTER_ADDR: "{{ ansible_host }}"
    labels:
      service: "portainer-agent"
      role: "management"
      managed_by: "ansible"
  become: true
  register: agent_container

- name: Wait for Portainer Agent to be ready
  ansible.builtin.wait_for:
    port: 9001
    host: "{{ ansible_host }}"
    delay: 2
    timeout: 30

- name: Display Portainer Agent information
  ansible.builtin.debug:
    msg:
      - "Portainer Agent has been deployed!"
      - "Agent endpoint: {{ ansible_host }}:9001"
      - "Container ID: {{ agent_container.container.Id[:12] }}"
      - "Add this endpoint in Portainer UI to manage remote Docker environments"