---
# Deployment tasks for portainer

- name: Pull Portainer image
  community.docker.docker_image:
    name: "{{ portainer_container_image }}"
    source: pull
    state: present
  become: true

- name: Deploy Portainer container
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    image: "{{ portainer_container_image }}"
    state: started
    restart_policy: "{{ portainer_container_restart_policy }}"
    networks:
      - name: "{{ portainer_network_name }}"
    ports:
      - "{{ portainer_web_port }}:9000"
      - "{{ portainer_agent_port }}:8000"
    volumes:
      - "{{ portainer_docker_socket }}:/var/run/docker.sock:ro"
      - "{{ portainer_data_dir }}:/data"
    env:
      PORTAINER_HIDE_LABELS: "{{ portainer_hide_labels | string }}"
    labels:
      service: "portainer"
      role: "management"
      managed_by: "ansible"
  become: true
  register: portainer_container

- name: Wait for Portainer to be ready
  ansible.builtin.uri:
    url: "http://localhost:{{ portainer_web_port }}/api/status"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 2

- name: Display Portainer access information
  ansible.builtin.debug:
    msg:
      - "Portainer has been successfully deployed!"
      - "Access URL: http://{{ ansible_host }}:{{ portainer_web_port }}"
      - "Container ID: {{ portainer_container.container.Id[:12] }}"
      - "Please complete initial setup via web interface"