---
# tasks file for portainer

- name: Include validation tasks
  ansible.builtin.include_tasks: validate.yml
  tags:
    - portainer
    - portainer-validate

- name: Include preparation tasks
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - portainer
    - portainer-prepare

- name: Include deployment tasks
  ansible.builtin.include_tasks: deploy.yml
  tags:
    - portainer
    - portainer-deploy

- name: Include SSL configuration tasks
  ansible.builtin.include_tasks: configure_ssl.yml
  when: portainer_ssl_enabled | bool
  tags:
    - portainer
    - portainer-ssl

- name: Include agent deployment tasks
  ansible.builtin.include_tasks: deploy_agent.yml
  when: portainer_deploy_agent | bool
  tags:
    - portainer
    - portainer-agent