---
# Preparation tasks for portainer

- name: Create portainer data directory
  ansible.builtin.file:
    path: "{{ portainer_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create certificates directory
  ansible.builtin.file:
    path: "{{ portainer_data_dir }}/certs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  when: portainer_ssl_enabled | bool

- name: Create docker network for management services
  community.docker.docker_network:
    name: "{{ portainer_network_name }}"
    driver: bridge
    state: present
  become: true

- name: Check if Portainer container exists
  community.docker.docker_container_info:
    name: "{{ portainer_container_name }}"
  register: portainer_container_info
  become: true

- name: Stop existing Portainer container if running
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    state: stopped
  when: portainer_container_info.exists
  become: true