---
# Validation tasks for portainer

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - portainer_container_name is defined
      - portainer_container_image is defined
      - portainer_web_port is defined
      - portainer_data_dir is defined
    fail_msg: "Required portainer variables are not defined"
    success_msg: "All required portainer variables are defined"

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false
  failed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed on {{ inventory_hostname }}. Please install Docker first."
  when: docker_version.rc != 0

- name: Validate port availability
  ansible.builtin.wait_for:
    port: "{{ portainer_web_port }}"
    state: stopped
    timeout: 3
  register: port_check
  failed_when: false

- name: Warn if port is already in use
  ansible.builtin.debug:
    msg: "Warning: Port {{ portainer_web_port }} appears to be in use on {{ inventory_hostname }}"
  when: port_check.failed is defined and port_check.failed