---
galaxy_info:
  author: PrivateBox Team
  description: Unbound recursive DNS resolver with DNSSEC support
  company: PrivateBox
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - dns
    - unbound
    - dnssec
    - security
    - privacy
    - resolver

dependencies: []