---
# PrivateBox-specific configuration
# These variables apply to all hosts in the privatebox group

# Service enable flags (for master control)
enable_adguard: true
enable_pihole: false  # Alternative to AdGuard
enable_unbound: false
enable_wireguard: false
enable_nginx_proxy: false

# --- AdGuard Home Configuration ---
adguard_enabled: "{{ enable_adguard }}"
adguard_image: "adguard/adguardhome"
adguard_version: "latest"

# AdGuard ports
adguard_web_port: 8080      # Web interface (avoid 80/443 conflicts)
adguard_dns_port: 53        # DNS service
adguard_dns_port_udp: 53    # DNS service UDP
adguard_setup_port: 3001    # Initial setup (avoid Semaphore's 3000)
adguard_dns_over_tls: 853   # DNS-over-TLS
adguard_dns_over_quic: 784  # DNS-over-QUIC

# AdGuard directories
adguard_data_dir: "{{ container_data_root }}/adguard"
adguard_config_dir: "{{ container_config_root }}/adguard"

# AdGuard resource limits
adguard_memory_limit: "512M"
adguard_cpu_quota: "50%"

# AdGuard configuration
adguard_admin_password: "ChangeMe123!"  # Change in production!
adguard_enable_dhcp: false
adguard_enable_filtering: true
adguard_enable_safebrowsing: true
adguard_enable_parental: false

# --- Pi-hole Configuration (Alternative) ---
pihole_enabled: "{{ enable_pihole }}"
pihole_image: "pihole/pihole"
pihole_version: "latest"

pihole_web_port: 8081
pihole_dns_port: 53
pihole_dns_port_udp: 53
pihole_dhcp_port: 67

pihole_data_dir: "{{ container_data_root }}/pihole"
pihole_config_dir: "{{ container_config_root }}/pihole"
pihole_dnsmasq_dir: "{{ container_config_root }}/pihole/dnsmasq.d"

pihole_memory_limit: "256M"
pihole_cpu_quota: "25%"

pihole_admin_password: "ChangeMe123!"  # Change in production!
pihole_timezone: "{{ timezone }}"
pihole_dns1: "1.1.1.1"
pihole_dns2: "1.0.0.1"

# --- Unbound DNS Configuration ---
unbound_enabled: "{{ enable_unbound }}"
unbound_image: "mvance/unbound"
unbound_version: "latest"

unbound_port: 5335  # Different port to work with AdGuard/Pi-hole
unbound_data_dir: "{{ container_data_root }}/unbound"
unbound_config_dir: "{{ container_config_root }}/unbound"

unbound_memory_limit: "256M"
unbound_cpu_quota: "25%"

# --- WireGuard Configuration ---
wireguard_enabled: "{{ enable_wireguard }}"
wireguard_image: "linuxserver/wireguard"
wireguard_version: "latest"

wireguard_port: 51820
wireguard_data_dir: "{{ container_data_root }}/wireguard"
wireguard_config_dir: "{{ container_config_root }}/wireguard"

wireguard_memory_limit: "256M"
wireguard_cpu_quota: "25%"

wireguard_peers: 5  # Number of peer configs to generate
wireguard_internal_subnet: "10.13.13.0"
wireguard_allowed_ips: "0.0.0.0/0"

# --- Service Discovery ---
service_urls:
  adguard: "http://{{ ansible_host }}:{{ adguard_web_port }}"
  pihole: "http://{{ ansible_host }}:{{ pihole_web_port }}/admin"
  semaphore: "http://{{ ansible_host }}:3000"
  portainer: "http://{{ ansible_host }}:9000"

# --- Backup Configuration ---
backup_services:
  - adguard
  - pihole
  - unbound
  - wireguard

# --- Monitoring ---
monitor_endpoints:
  adguard_web: "{{ service_urls.adguard }}"
  adguard_dns: "{{ ansible_host }}:{{ adguard_dns_port }}"
  pihole_web: "{{ service_urls.pihole }}"
  pihole_dns: "{{ ansible_host }}:{{ pihole_dns_port }}"