---
# Deploy Management Services Playbook
# Deploys Portainer for container management and Semaphore for Ansible UI

- name: Deploy Management Services
  hosts: management_hosts
  gather_facts: true
  become: true
  tags:
    - management
    - deployment
  
  pre_tasks:
    - name: Check Docker installation
      ansible.builtin.command: docker --version
      register: docker_check
      changed_when: false
      failed_when: false
      tags:
        - docker-check

    - name: Install Docker if not present
      ansible.builtin.include_tasks: tasks/install_docker.yml
      when: docker_check.rc != 0
      tags:
        - docker
        - prerequisites

    - name: Ensure management directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/privatebox/portainer
        - /opt/privatebox/semaphore
        - /opt/privatebox/data
      tags:
        - directories

  tasks:
    - name: Deploy Portainer
      ansible.builtin.include_role:
        name: portainer
      vars:
        portainer_data_dir: /opt/privatebox/portainer/data
        portainer_enable_ssl: true
        portainer_admin_password: "{{ vault_portainer_admin_password }}"
      tags:
        - portainer
        - containers
      when: portainer_enabled | default(true)

    - name: Deploy Semaphore
      ansible.builtin.include_role:
        name: semaphore
      vars:
        semaphore_db_type: postgres
        semaphore_db_host: localhost
        semaphore_db_name: semaphore
        semaphore_admin_user: admin
        semaphore_admin_password: "{{ vault_semaphore_admin_password }}"
      tags:
        - semaphore
        - ansible-ui
      when: semaphore_enabled | default(true)

    - name: Configure Portainer-Semaphore integration
      ansible.builtin.include_tasks: tasks/configure_management_integration.yml
      tags:
        - integration
        - configuration
      when: 
        - portainer_enabled | default(true)
        - semaphore_enabled | default(true)

    - name: Setup management service backups
      ansible.builtin.include_tasks: tasks/setup_management_backups.yml
      tags:
        - backups
        - maintenance

  post_tasks:
    - name: Wait for Portainer to be ready
      ansible.builtin.uri:
        url: "https://{{ ansible_default_ipv4.address }}:9443/api/system/status"
        validate_certs: false
        status_code: 200
      register: portainer_status
      until: portainer_status.status == 200
      retries: 30
      delay: 10
      when: portainer_enabled | default(true)
      tags:
        - validation
        - portainer-check

    - name: Wait for Semaphore to be ready
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:3000/api/ping"
        status_code: 200
      register: semaphore_status
      until: semaphore_status.status == 200
      retries: 30
      delay: 10
      when: semaphore_enabled | default(true)
      tags:
        - validation
        - semaphore-check

    - name: Configure initial Semaphore project
      ansible.builtin.include_tasks: tasks/configure_semaphore_project.yml
      run_once: true
      when: semaphore_enabled | default(true)
      tags:
        - semaphore-config
        - initial-setup

    - name: Generate management services URLs
      ansible.builtin.template:
        src: templates/management_urls.j2
        dest: /etc/privatebox/management_urls.txt
      tags:
        - documentation
        - urls

    - name: Create deployment marker
      ansible.builtin.file:
        path: /etc/privatebox/.management_deployed
        state: touch
      tags:
        - marker

  handlers:
    - name: restart portainer
      ansible.builtin.systemd:
        name: portainer
        state: restarted
      become: true

    - name: restart semaphore
      ansible.builtin.systemd:
        name: semaphore
        state: restarted
      become: true

    - name: restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
      become: true