---
# Network services group variables

# OPNsense configuration
opnsense_version: "23.7"
opnsense_vm_id: 101
opnsense_hostname: opnsense
opnsense_domain: "{{ privatebox_domain }}"
opnsense_admin_password: "{{ vault_opnsense_admin_password }}"
opnsense_vm_cores: 2
opnsense_vm_memory: 2048
opnsense_vm_disk_size: 20
opnsense_wan_interface: vtnet0
opnsense_lan_interface: vtnet1
opnsense_lan_ip: 10.10.20.1
opnsense_lan_netmask: 24

# Unbound DNS configuration
unbound_container_id: 102
unbound_hostname: unbound
unbound_listen_addresses:
  - 10.10.10.5
  - 127.0.0.1
unbound_port: 53
unbound_access_control:
  - "10.10.0.0/16 allow"
  - "127.0.0.0/8 allow"
unbound_forward_zones: []
unbound_cache_size: 256m
unbound_num_threads: 2
unbound_prefetch: true
unbound_prefetch_key: true
unbound_serve_expired: true
unbound_aggressive_nsec: true

# AdGuard Home configuration
adguard_container_id: 103
adguard_hostname: adguard
adguard_web_port: 3000
adguard_dns_port: 53
adguard_listen_addresses:
  - 10.10.10.6
adguard_upstream_dns:
  - 10.10.10.5  # Unbound
  - tls://dns.quad9.net
  - tls://cloudflare-dns.com
adguard_bootstrap_dns:
  - 9.9.9.9
  - 1.1.1.1
adguard_blocklists:
  - name: "AdGuard Base"
    url: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
  - name: "AdGuard Mobile"
    url: "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt"
  - name: "EasyList"
    url: "https://easylist.to/easylist/easylist.txt"
  - name: "EasyPrivacy"
    url: "https://easylist.to/easylist/easyprivacy.txt"
  - name: "Malware Domains"
    url: "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-ag.txt"

# Network monitoring
network_monitoring_enabled: true
traffic_analysis_enabled: true