---
# OPNsense role handlers

- name: restart opnsense
  ansible.builtin.uri:
    url: "https://{{ opnsense_api.host }}:{{ opnsense_api.port }}/api/core/system/reboot"
    method: POST
    validate_certs: "{{ opnsense_api.verify_ssl }}"
    force_basic_auth: true
    user: "{{ opnsense_api.username }}"
    password: "{{ opnsense_api.password }}"
    status_code: 200
  delegate_to: localhost

- name: reload firewall
  ansible.builtin.uri:
    url: "https://{{ opnsense_api.host }}:{{ opnsense_api.port }}/api/firewall/filter/apply"
    method: POST
    validate_certs: "{{ opnsense_api.verify_ssl }}"
    force_basic_auth: true
    user: "{{ opnsense_api.username }}"
    password: "{{ opnsense_api.password }}"
    status_code: 200
  delegate_to: localhost

- name: reconfigure interfaces
  ansible.builtin.uri:
    url: "https://{{ opnsense_api.host }}:{{ opnsense_api.port }}/api/interfaces/reconfigure"
    method: POST
    validate_certs: "{{ opnsense_api.verify_ssl }}"
    force_basic_auth: true
    user: "{{ opnsense_api.username }}"
    password: "{{ opnsense_api.password }}"
    status_code: 200
  delegate_to: localhost