---
# Proxmox-specific variables

# Proxmox API configuration
proxmox_api_host: "{{ inventory_hostname }}"
proxmox_api_port: 8006
proxmox_api_validate_certs: false

# Storage configuration
proxmox_storage_default: local-lvm
proxmox_storage_iso: local
proxmox_storage_backup: local

# VM defaults
proxmox_vm_cpu_type: host
proxmox_vm_cpu_cores: 2
proxmox_vm_memory: 2048
proxmox_vm_disk_size: 20
proxmox_vm_disk_format: qcow2
proxmox_vm_network_bridge: vmbr0
proxmox_vm_network_model: virtio
proxmox_vm_start_on_boot: true

# Container defaults
proxmox_ct_cpu_cores: 1
proxmox_ct_memory: 512
proxmox_ct_disk_size: 8
proxmox_ct_network_bridge: vmbr0
proxmox_ct_start_on_boot: true
proxmox_ct_unprivileged: true

# Backup configuration
proxmox_backup_enabled: true
proxmox_backup_schedule: "0 2 * * *"
proxmox_backup_mode: snapshot
proxmox_backup_compression: zstd
proxmox_backup_retention: 7

# Resource pools
proxmox_pools:
  - name: network-services
    comment: "Network services (OPNsense, DNS)"
  - name: management
    comment: "Management services (Portainer, Semaphore)"
  - name: privacy-services
    comment: "Privacy services (VPN, Tor)"

# VM ID allocation ranges
proxmox_vmid_ranges:
  network: 100-199
  management: 200-299
  privacy: 300-399
  testing: 900-999